# Overview
Clustering patient data provides a powerful framework for uncovering latent structure in heart-transplant survival that may be obscured in traditional modeling approaches. By segmenting patients based on pre-transplant characteristics—including demographics, clinical history, hemodynamics, comorbidities, and laboratory values—we aim to identify clinically meaningful subgroups that differ in risk profiles, physiological presentation, and post-transplant outcomes.

While clustering is inherently exploratory rather than predictive, it plays a critical role in revealing population heterogeneity and identifying candidate phenotypes that may not be well captured through standard regression-based methods. This is particularly relevant when examining gender-specific survival patterns, where complex interactions among biological, clinical, and social factors may give rise to distinct patient subpopulations that are difficult to model parametrically.

In this study, we leverage data from the United Network for Organ Sharing (UNOS) covering the most recent 10-year period to ensure temporal consistency across clinical practice, allocation policies, and data completeness. This constrained time horizon reduces confounding from long-term systemic changes and enables more interpretable, era-specific characterization of both recipient and donor profiles. By jointly analyzing these features, we aim to better understand how patient-donor interactions, including gender related differences, contribute to variation in post-transplant survival outcomes.

In [1]:
# path to user functions
import sys  
sys.path.append('../Src/')

import pandas as pd
from pandas.api.types import CategoricalDtype
import numpy as np
from scipy import stats
import sys
from importlib.metadata import version

# initializing variables
SEED = 1776

# python modules
import utilities as u

# Create a dictionary of versions
versions = {
    "Python": sys.version.split()[0],
    "Pandas": pd.__version__,
    "NumPy": np.__version__,
    "Scipy": sys.modules['scipy'].__version__,
}

# Display as a clean DataFrame
df_versions = pd.DataFrame(list(versions.items()), columns=['Library', 'Version'])
print(df_versions)

# adjust pandas display options to max
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
# adjust pandas display options to ensure full display of content
pd.set_option('display.max_colwidth', None)

  Library  Version
0  Python  3.11.13
1  Pandas    2.3.1
2   NumPy    2.3.2
3   Scipy   1.16.1

## Import Data

In [2]:
# import discretized data
df = pd.read_pickle("../Data/Heart_main.pkl")
df_dict =  pd.read_pickle("../Data/Dict_main.pkl")

In [3]:
df.head()

,PreviousTransplantNumber_CAN,WaitListDiagnosisCode_CAN,INUTERO,Gender_CAN,BloodGroup_CAN,Weight_kg_Registrsation_CAN,Height_cm_Registration_CAN,BMI_Listing_CAN,Citizenship_CAN,ResidencyStateRegistration_CAN,EducationLevel_CAN,LifeSupportRegistration_ECMO_CAN,LifeSupportRegistration_IABP_CAN,LifeSupportInhaled_CAN,InotropesIVRegistration_CAN,LifeSupportRegistration_PGE_CAN,LifeSupportMechanismRegistration_OTHER_CAN,VentricularDeviceTypeRegistration_CAN,VentricularDeviceBrandRegistration_CAN,FunctionalStatusRegistration_CAN,PrimaryPaymentRegistration_CAN,DiagnosisAtListing_CAN,DiabetesType_CAN,DialysisTypeRegistration_CAN,CerebroVascularDisease_CAN,PreviousMalignancy_CAN,CreatinineRegistration_CAN,TotalSerumAlbuminRegistration_CAN,DefibrillatorImplantRegistration_CAN,HemodynamicsRegistration_SYS_CAN,HemodynamicsRegistration_PA_DIA_CAN,HemodynamicsRegistration_PA_MN_CAN,HemodynamicsRegistration_PCW_CAN,HemodynamicsRegistration_CO_CAN,InotropesVasodilatorsRegistration_SYS_CAN,InotropesVasodilatorsRegistration_DIA_CAN,InotropesVasodilatorsRegistration_MN_CAN,InotropesVasodilatorsRegistration_PCW_CAN,InotropesVasodilatorsRegistration_CO_CAN,CigaretteUse_CAN,CigaretteAbstinence_CAN,PriorCardiacSurgery_CAN,PriorCardiacSurgeryType_CAN,PriorCardiacSurgeryTypeText_CAN,DAYS_STAT1,StatusDays_1A,StatusDays_2,StatusDays_1B,StatusDays_A4,StatusDays_A5,StatusDays_A2,StatusDays_A3,StatusDays_1,StatusDays_A6,LastInactiveStatusReason,InitialWaitingListStatusCode_CAN,ReasonRemovalWaitingList_CAN,ReceivedDeceasedDonorTramsplant_CAN,TotalDayWaitList_CAN,StatusAtTransplant_CAN,Age_Listing_CAN,LifeSupportRegistration_CAN,AllocationBeginDate_CAN,RemovalWaitListDate_CAN,InitialWaitListDate_CAN,Hispanic_CAN,Ethnicity_CAN,Height_cm_Listing_CAN,Weight_kg_Listing_CAN,BMI_Listing_CALC_CAN,Height_cm_Removal_CAN,Weight_kg_Removal_CAN,BMI_Removal_CAN,COMPOSITE_DEATH_DATE,VentilatorRegistration_CAN,TransplantRegion_CAN,ValidationDateTCR_CAN,WorkIncomeRegistration_CAN,AntigenBW4_CAN,AntigenBW6_CAN,AntigenC1_CAN,AntigenC2_CAN,AntigenDR51_CAN,AntigenDR51_2_CAN,AntigenDR52_CAN,AntigenDR52_2_CAN,AntigenDR53_CAN,AntigenDR53_2_CAN,AntigenDQ1_CAN,AntigenDQ2_CAN,FunctionalStatusTransplant_CAN,MedicalConditionTransplant_CAN,STATUS_TRR,AdmissionDate_CAN,PrimaryPaymentTransplant_CAN,LifeSupportTransplant_ECMO_CAN,ResidencyStateTransplant_CAN,WorkIncomeTransplant_CAN,LifeSupportTransplant_PGE_CAN,CreatinineTransplant_CAN,DialysisBetweenRegistrationTransplant_CAN,HemodynamicsTransplant_CO_CAN,HemodynamicsTransplant_PA_DIA_CAN,HemodynamicsTransplant_PA_MN_CAN,HemodynamicsTransplant_PCW_CAN,HemodynamicsTransplant_SYS_CAN,LifeSupportTransplant_IABP_CAN,InfectionTherapyIV_CAN,InotropesIVTransplant_CAN,InotropesVasodilatorsTransplant_CO_CAN,InotropesVasodilatorsTransplant_DIA_CAN,InotropesVasodilatorsTransplant_MN_CAN,InotropesVasodilatorsTransplant_PCW_CAN,InotropesVasodilatorsTransplant_SYS_CAN,LifeSupportMechanismTransplant_OTHER_CAN,PriorLungSurgeryAfterRegistration_CAN,AirwayDehiscencePostTransplant,AcuteRejectionEpisode,StrokePostTransplant,DialysisPostDischarge,PacemakerPostTransplant,SteroidsUse_CAN,TotalBilirubinTransplant_CAN,TransfusionAfterRegistration_CAN,VentricularDeviceTypeTransplant_CAN,VentricularDeviceBrandTransplant_CAN,VentilatorySupport_CAN,VentilatorTransplant_CAN,LifeSupportInhaledTransplant_CAN,PriorCardiacSurgeryTypeListAndTransplant_CAN,Hepatitis_B_CoreAntibody_CAN,SurfaceAntigenHEP_B_CAN,SurfaceHBVAntibodyTotalTransplant_CAN,CMVStatus_Transplant_CAN,HIV_SeroStatusTransplant_CAN,HEP_C_SerostatusStatus_CAN,EpsteinBarrSeroStatusTransplant_CAN,HIV_NAT_PreTransplant_CAN,HCV_NAT_PreTranspant_CAN,HBV_NAT_Result_CAN,COD,GraftFailStatus,GraftLifeSpanDay,LastFollowupNumber,TransplantStatus,TransplantSurvivalDay,RecipientStatus,FunctionalStatusFollowUp,TXHRT,TransplantProcedure_CAN,STATUS_TCR,LifeSupportInhaledRegistration_CAN,DeceasedRetyped_DON,CrossMatchDone,CPRA_Recent_CAN,CPRA_Peak_CAN,RejectionTreatmentWithinOneYear,PreviousTransplantSameOrgan_CAN,PreviousTransplantAnyOrgan_CAN,AntigenDA1_DON,AntigenDA2_DON,AntigenDB1_DON,AntigenDB2_DON,AntigenDDR1_DON,AntigenDDR2_DON,AntigenRA1_CAN,AntigenRA2_CAN,AntigenRB1_CAN,AntigenRB2_CAN,AntigenRDR1_CAN,AntigenRDR2_CAN,MismatchLevel_AMIS,MismatchLevel_BMIS,MismatchLevel_DRMIS,MismatchLevel_HLAMIS,Class1PRA_TransplantPercentage_CAN,Class2PRA_TransplantPercentage_CAN,MalignancyBetweenRegistrationTransplant_CAN,CMV_IGG_Transplant_CAN,CMV_IGM_Transplant_CAN,Citizenship_DON,PastCocaineUse_DON,Age_DON,Ethnicity_DON,Hepatitis_B_CoreAntibody_DON,SurfaceAntigenHEP_B_DON,BloodGroup_DON,HeavyAlcoholUse_DON,DeceasedOrLiving_DON,Gender_DON,ResidencyState_DON,Antibody_HEP_C_DON,NonHeartBeating_DON,AntiHypertensive_DON,BloodInfectionSource_DON,BloodUreaNitrogenLevel_DON,Creatinine_DON,OtherInfectionSource_DON,Diuretics_DON,SteroidsUse_DON,TriiodothyronineT3_DON,ThyroxineT4_DON,OtherMedsText2_DON,OtherMedsText3_DON,OtherMedsText1_DON,PulmonaryInfection_DON,PULM_INF_CONF_DON,Level_SGOT_AST_DON,Level_SGOT_ALT_DON,TerminalTotalBilirubin_DON,UrineInfection_DON,Vasodilators_DON,AntibodyResultRPR_VDRL_DON,InfectionClinical_DON,CocaineUse_DON,OtherDrugUse_DON,CancerExtraCranial_DON,CancerSite_DON,CigaretteHistory_DON,HypertensionHistory_DON,CancerIntraCranial_DON,CancerHistory_DON,DiabetesHistory_DON,Diabetes_DON,PastOtherDrugUse_DON,CancerSkin_DON,SerologyAntiCMV_DON,CauseOfDeath_DON,SyntheticAntiDiureticHormone_DON,DeathCircumstance_DON,DeathMechanism_DON,OrganRecoveryDate_DON,HeparinManagement_DON,ArginnieManagement_DON,InsulinManagement_DON,Height_cm_DON,Weight_kg_DON,BMI_Donation_DON,HBV_NAT_Result_DON,HCV_NAT_Result_DON,HIV_NAT_Result_DON,StatusDate_CAN,TransplantDate_CAN,CenterDischargeDate_CAN,TransplantType_CAN,BloodGroupMatchLevel,Age_CAN,PrimaryDiagnosisType_CAN,DialysisPriorRegistration_CAN,IschemicTimeHour_DON,GraftStatus,AllocationType_DON,LengthOfStay,LifeSupportTransplant_CAN,PriorCardiacSurgeryListAndTransplant_CAN,Malignancy_CAN,Height_cm_CAN,Weight_kg_CAN,BMI_Calc_CAN,DistanceFromDonorHospitaltoTXCenter_CAN,VentilatorySupportAfterRegistration_CAN,HeartProcedureType_CAN,ValidationDateTRR_CAN,AdmissionDate_DON,UrineProtein_DON,CardiacArrest_DON,LungPO2_DON,MyocardialInfarctionHistory_DON,LV_EjectionFractionMedthod_DON,LV_EjectionFractionPercent_DON,CoronaryAngiogram_DON,Biopsy_DON,Tatoos_DON,STATUS_DDR,ValidationDateTCR_DDR,AntibodyResultHBSAB_DON,EpsteinBarr_IGG_DON,EpsteinBarr_IGM_DON,HIV_Risk_DON,InotropicAgent_DON,KidneyAllocation_DON,TransplantYear_CAN,InotropicMedicationProcurement_DON,ReferralDate_DON,ListingYear_CAN,TransfusionNumber_DON,LungPO2_Done_DON,LungPO2_FIO2_DON,OrganRecovery_PCO2_DON,PulmonaryCatheter_DON,BronchoscopyLeft_DON,BronchoscopyRight_DON,ChestXray_DON,BloodPH_DON,Hematocrit_DON
0,0,DILATED MYOPATHY: IDIOPATHIC,NaN,M,A,65.771,173.0,22.0470,US Citizen,CA,ATTENDED COLLEGE/TECHNICAL SCHOOL,No,No,No,No,No,Yes,Lvad+Rvad,CentriMag (Thoratec/Levitronix),"10% - Moribund, fatal processes progressing rapidly",Public insurance - Medicaid,DILATED MYOPATHY: IDIOPATHIC,No,No dialysis,No,No,1.3,4.8,Yes,50.0,34.0,37.0,36.0,2.50,Yes,Yes,Yes,Yes,Yes,No,Unknown,Yes,Valve Replace/Repair,NaN,0,11,0,0,0,0,0,0,0,0,NaN,HR: Status 1A,4,Yes,11.0,Hypoplastic Left Heart Syndrome; Atrioventricular Septal Defect; Other left Heart Valvar/Structural,45,Yes,2013-01-18,2013-01-29,2013-01-18,Hispanic/Latino,Hispanic,172.7,65.8,22.0,172.7,65.8,22.0,2013-12-24 00:00:00,No,Region 5,1995-02-28 00:00:00,No,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,"10% - Moribund, fatal processes progressing rapidly",In Intensive Care Unit,V,2012-12-25,Public insurance - Medicaid,No,CA,No,No,1.00,No,NaN,NaN,NaN,NaN,NaN,No,No,No,Unknown,Unknown,Unknown,Unknown,Unknown,Yes,No,No,3,No,Yes,No,No,3.6,No,Lvad+Rvad,CentriMag (Thoratec/Levitronix),Yes,No,No,"Other, specify",Negative,Negative,Unknown,Positive,Negative,Negative,Not Done,Unknown,Unknown,Unknown,2204,Failure,329.0,999,Dead,329.0,Dead,"100% - Normal, no complaints, no evidence of disease",Yes,501,V,No,No,No,NaN,NaN,No,No,No,2,29,44,49,4,15,24,24,35,61,4,4,2,2,1,5,2.0,0.0,No,Positive,Negative,US Citizen,No,31,Black,Negative,Negative,A,No,Deceased Donor,M,CA,Negative,No,Yes,No,18.0,1.30,No,Yes,No,No,No,"KCL,","DOPAMINE, VASOPRESSIN,","ZOSYN, VANCOMYCIN",Yes,Yes,46.0,40.0,0.4,No,No,Negative,Yes,Unknown,Unknown,No,NO,No,No,No,No,No,No,No,No,Positive,HEAD TRAUMA,Yes,HOMICIDE,GUNSHOT WOUND,2013-01-29,Yes,No,Yes,172.7,107.0,35.867286,Unknown,Unknown,Unknown,2013-12-24,2013-01-29,2013-04-15,O,Identical,45,DILATED MYOPATHY: IDIOPATHIC,No,4.9,No,Local,76.0,Yes,Yes,No,172.7,65.3,21.9,83.0,Yes,Orthotopic Bicaval,2013-03-07 19:06:35,2013-01-27,No,No,182.0,No,Echo,60.0,No,Biopsy not done,Yes,V,2013-02-27 16:31:42,Not Done,Positive,Negative,No,Unknown,No,2013,No,2013-01-27,2013,1 - 5,Yes,47.0,40.0,No,Normal,Normal,Abnormal-right,7.38,26.2
1,0,DILATED MYOPATHY: OTHER SPECIFY,N,M,O,72.575,185.0,21.1093,US Citizen,TX,HIGH SCHOOL (9-12) or GED,No,No,No,No,No,No,Lvad,Heartmate II,"10% - Moribund, fatal processes progressing rapidly",Public insurance - Medicare FFS (Fee for Service),DILATED MYOPATHY: VIRAL,No,No dialysis,No,No,2.3,2.9,Yes,53.0,39.0,46.0,31.0,2.10,No,No,No,No,No,No,Unknown,No,Unknown,NaN,0,3,0,263,0,0,0,0,0,0,11,HR: Status 1A,4,Yes,348.0,Transposition of the Great Arteries; Truncus Arteriosus; Congenitally Corrected Transposition (L-TGA),35,Yes,2012-02-15,2013-01-28,2012-02-15,Hispanic/Latino,Hispanic,185.4,72.6,21.1,185.4,72.6,21.1,998,No,Region 4,1994-05-09 00:00:00,No,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,90% - Able to carry on normal activity: minor symptoms of disease,Not Hospitalized,V,2013-01-28,Public insurance - Medicare FFS (Fee for Service),No,TX,No,No,0.70,No,4.60,8.0,18.0,4.0,28.0,No,No,No,No,No,No,No,No,No,No,No,3,No,No,No,No,0.9,No,Lvad,Heartmate II,No,No,No,Unknown,Negative,Negative,Unknown,Positive,Negative,Negative,Positive,Unknown,Unknown,Unknown,998,Success,2592.0,80,Alive,2592.0,Living,Unknown,Yes,501,V,No,Yes,Yes,NaN,NaN,Unknown,No,No,2,68,49,60,10,16,30,68,48,65,8,9,1,2,2,5,0.0,0.0,No,Positive,Negative,Non-US Citizen/US Resident,No,30,Hispanic,Negative,Negative,O,No,Deceased Donor,M,TX,Negative,No,No,No,29.0,0.70,No,Yes,No,No,Yes,NaN,NaN,"ANCEF, FENTANYL, VERSED,LASIX",Yes,Yes,38.0,171.0,0.8,No,No,Negative,Yes,Unknown,Unknown,No,NO,No,No,No,No,No,No,No,No,Positive,HEAD TRAUMA,No,"Accident, Non-MVA",BLUNT INJURY,2013-01-28,Yes,Yes,No,172.7,67.1,22.492476,Unknown,Unknown,Unknown,2020-03-04,2013-01-28,2013-02-07,O,Identical,36,DILATED MYOPATHY: IDIOPATHIC,No,3.1,Yes,Local,10.0,Yes,No,No,185.4,94.8,27.6,0.0,No,Orthotopic Bicaval,2013-02-11 16:24:00,2013-01-12,No,No,323.0,No,Echo,55.0,No,Biopsy not done,No,V,2013-03-03 21:46:46,Not Done,Positive,Negative,No,Dopamine,No,2013,Yes,2013-01-26,2012,6 - 10,Yes,100.0,28.0,No,Normal,Normal,Abnormal-left,7.50,27.8
2,0,DILATED MYOPATHY: ISCHEMIC,N,M,O,106.000,175.0,34.5096,US Citizen,NY,ATTENDED COLLEGE/TECHNICAL SCHOOL,Yes,Yes,No,No,No,No,None,Unknown,"10% - Moribund, fatal processes progressing rapidly",Private insurance,DILATED MYOPATHY: ISCHEMIC,No,No dialysis,No,No,1.4,2.2,No,52.0,23.0,32.0,NaN,5.00,Yes,Yes,Yes,Unknown,Yes,No,Unknown,Yes,"CABG; Other, specify",VSD,0,53,0,2,0,0,0,0,0,0,NaN,HR: Status 1A,4,Yes,55.0,Hypoplastic Left Heart Syndrome; Atrioventricular Septal Defect; Other left Heart Valvar/Structural,58,Yes,2012-12-06,2013-01-30,2012-12-06,Non-Hispanic/Non-Latino,"White, Non-Hispanic",175.3,106.0,34.5,175.3,106.0,34.5,998,Yes,Region 9,NaT,No,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,"20% - Very sick, hospitalization necessary: active treatment necessary",Hospitalized Not in ICU,V,2012-11-21,Private insurance,No,NY,No,No,2.19,No,4.40,21.0,22.0,13.0,28.0,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,3,No,No,No,No,1.2,Yes,None,Unknown,Yes,No,No,"CABG; Other, specify",Negative,Negative,Unknown,Negative,Negative,Negative,Positive,Unknown,Unknown,Unknown,998,Success,2913.0,80,Alive,2913.0,Living,Unknown,Yes,501,V,No,No,Yes,NaN,NaN,No,No,No,2,3,7,44,11,15,2,3,35,44,4,13,0,1,2,3,0.0,0.0,No,Negative,Negative,US Citizen,No,15,"White, Non-Hispanic",Negative,Negative,O,No,Deceased Donor,M,NY,Negative,No,No,No,15.0,0.74,No,Yes,Yes,No,Yes,"AMPHOTERICIN, BETADINE",ZANTAC,"ZOSYN, VANCOMYCIN",Yes,Yes,445.0,217.0,0.7,No,No,Negative,Yes,Unknown,Yes,No,NO,No,No,No,No,No,No,Yes,No,Negative,ANOXIA,No,NONE OF THE ABOVE,DRUG INTOXICATION,2013-01-30,Yes,Yes,No,170.0,59.0,20.415225,Unknown,Unknown,Unknown,2021-01-21,2013-01-30,2013-02-20,O,Identical,58,DILATED MYOPATHY: ISCHEMIC,No,1.4,Yes,Local,21.0,Yes,Yes,No,175.3,90.7,29.5,0.0,Yes,Orthotopic Bicaval,2013-04-22 17:29:07,2013-01-26,No,No,401.0,No,Echo,60.0,No,Biopsy not done,No,V,2013-02-15 14:07:33,Not Done,Negative,Negative,No,"Other, specify",No,2013,Yes,2013-01-27,2012,NONE,Yes,100.0,41.0,No,Normal,Unknwn,Abnormal-both,7.40,25.4
3,0,DILATED MYOPATHY: ISCHEMIC,N,M,A,111.000,178.0,35.0335,US Citizen,NY,HIGH SCHOOL (9-12) or GED,No,No,No,Yes,No,No,Lvad+Rvad,CentriMag (Thoratec/Levitronix),"20% - Very sick, hospitalization necessary: active treatment necessary",Public insurance - Medicare & Choice,DILATED MYOPATHY: ISCHEMIC,No,No dialysis,No,No,1.1,3.1,No,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown,Unknown,Unknown,Unknown,Yes,0-2 months,Yes,"Other, specify",VAD PLACEMENT,0,96,0,296,0,0,0,0,0,0,NaN,HR: Status 1A,4,Yes,392.0,Hypoplastic Left Heart Syndrome; Atrioventricular Septal Defect; Other left Heart Valvar/Structural,65,Yes,2012-01-03,2013-01-29,2012-01-03,Non-Hispanic/Non-Latino,"White, Non-Hispanic",178.0,111.0,35.0,178.0,111.6,35.2,2016-06-07 00:00:00,No,Region 9,1992-05-08 00:00:00,No,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,80% - Normal activity with effort: some symptoms of disease,Not Hospitalized,V,2013-01-28,Private insurance,No,NY,No,No,1.35,No,4.80,12.0,22.0,12.0,34.0,No,No,No,No,No,No,No,No,No,No,No,1,No,No,No,No,0.7,Yes,Lvad,Heartmate II,Yes,No,No,"Other, specify",Negative,Negative,Unknown,Negative,Negative,Negative,Positive,Unknown,Unknown,Unknown,2003,Failure,1225.0,999,Dead,1225.0,Dead,"30% - Severely disabled: hospitalization is indicated, death not imminent",Yes,501,V,No,Yes,Yes,NaN,NaN,Yes,No,No,33,68,39,51,1,8,24,26,35,38,4,11,2,2,2,6,0.0,0.0,No,Negative,Not Done,US Citizen,No,47,"White, Non-Hispanic",Negative,Negative,A1,No,Deceased Donor,F,NY,Negative,No,Yes,Yes,29.0,1.34,No,Yes,Yes,No,Yes,"D50, DOPAMINE, DIFLUCAN",NaN,"KCL, VANCO, MAG, ZOSYN",Yes,Yes,248.0,165.0,0.3,Yes,No,Negative,Yes,Unknown,Yes,No,"SKIN - SQUAMOUS, BASAL CELL",Yes,Yes,No,Yes,No,No,Yes,No,Positive,CEREBROVASCULAR/STROKE,No,DEATH FROM NATURAL CAUSES,INTRACRANIAL HEMORRHAGE/STROKE,2013-01-29,Yes,Yes,Yes,163.0,115.2,43.358802,Unknown,Unknown,Unknown,2016-06-07,2013-01-29,2013-03-02,O,Identical,66,DILATED MYOPATHY: ISCHEMIC,No,3.5,No,Regional,32.0,Yes,Yes,No,177.8,113.0,35.7,252.0,Yes,Orthotopic Bicaval,2013-03-07 17:18:31,2013-01-27,Yes,No,267.0,No,Echo,60.0,"Yes, normal",Biopsy not done,Yes,V,2013-02-27 11:41:18,Not Done,Positive,Negative,No,Unknown,No,2013,No,2013-01-27,2012,NONE,Yes,100.0,36.0,No,Unknwn,Unknwn,Abnormal-both,7.37,38.3
4,0,DILATED MYOPATHY: IDIOPATHIC,N,M,A,72.000,172.0,24.3375,US Citizen,NC,ASSOCIATE/BACHELOR DEGREE,No,No,No,No,No,No,Lvad,Heartmate II,90% - Able to carry on normal activity: minor symptoms of disease,Public insurance - Medicare & Choice,VALVULAR HEART DISEASE,No,No dialysis,No,No,0.8,NaN,Yes,30.0,15.0,20.0,15.0,4.75,No,No,No,No,No,No,Unknown,Yes,"Other, specify",LVAD IMPLANT,0,19,0,23,0,0,0,0,0,0,NaN,HR: Status 1B,4,Yes,42.0,Hypoplastic Left Heart Syndrome; Atrioventricular Septal Defect; Other left Heart Valvar/Structural,70,Yes,2012-12-19,2013-01-30,2012-12-19,Non-Hispanic/Non-Latino,"White, Non-Hispanic",172.0,72.0,24.3,172.0,72.0,24.3,998,No,Region 11,1995-02-02 08:20:06,No,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,90% - Able to carry on normal activity: minor symptoms of disease,Not Hospitalized,V,2013-01-29,Public insurance - Medicare & Choice,No,NC,No,No,0.80,No,4.75,15.0,20.0,15.0,30.0,No,No,No,No,No,No,No,No,No,No,No,3,No,No,No,No,0.8,No,Lvad,Heartmate II,No,No,No,Unknown,Negative,Negative,Unknown,Positive,Negative,Negative,Positive,Unknown,Unknown,Unknown,998,Success,2785.0,80,Alive,2785.0,Living,Unknown,Yes,501,V,No,Yes,Yes,NaN,NaN,No,No,No,3,24,61,64,7,15,3,24,7,38,13,14,0,2,2,4,0.0,0.0,No,Positive,Negative,US Citizen,No,22,"White, Non-Hispanic",Negative,Negative,A2,No,Deceased Donor,F,NC,Negative,No,Yes,No,70.0,5.10,No,Yes,Yes,No,Yes,"ZOSYN, CIPROFLOXACIN","BUMETIDE, ANCEF","ROCURONIUM, VECURONIUM",Yes,Yes,137.0,174.0,0.5,No,No,Negative,Yes,Unknown,Yes,No,NO,No,No,No,No,No,No,Yes,No,Positive,ANOXIA,No,SUICIDE,DRUG INTOXICATION,2013-01-30,Yes,No,Yes,182.9,113.0,33.786719,Unknown,Unknown,Unknown,2020-09-15,2013-01-30,2013-02-25,O,Identical,70,DILATED MYOPATHY: IDIOPATHIC,No,2.8,Yes,Local,26.0,Yes,No,No,173.0,72.0,24.1,60.0,No,Orthotopic Bicaval,2013-03-13 17:15:33,2013-01-25,No,Yes,209.0,No,Echo,55.0,No,Biopsy not done,Yes,V,2013-02-11 12:44:02,Positive,Positive,Negative,No,Unknown,No,2013,No,2013-01-28,2012,NONE,Yes,100.0,33.0,No,Normal,Unknwn,Abnormal-both,7.51,30.7

In [4]:
df.info(max_cols=df.shape[1])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30725 entries, 0 to 30724
Data columns (total 295 columns):
 #    Column                                        Non-Null Count  Dtype
---   ------                                        --------------  -----
 0    PreviousTransplantNumber_CAN                  30725 non-null  category
 1    WaitListDiagnosisCode_CAN                     30725 non-null  category
 2    INUTERO                                       6319 non-null   object
 3    Gender_CAN                                    30725 non-null  category
 4    BloodGroup_CAN                                30725 non-null  category
 5    Weight_kg_Registrsation_CAN                   30673 non-null  float64
 6    Height_cm_Registration_CAN                    30608 non-null  float64
 7    BMI_Listing_CAN                               30606 non-null  float64
 8    Citizenship_CAN                               30725 non-null  category
 9    ResidencyStateRegistration_CAN                30725 non-null  category
 10   EducationLevel_CAN                            30725 non-null  category
 11   LifeSupportRegistration_ECMO_CAN              30725 non-null  category
 12   LifeSupportRegistration_IABP_CAN              30725 non-null  category
 13   LifeSupportInhaled_CAN                        30725 non-null  category
 14   InotropesIVRegistration_CAN                   30725 non-null  category
 15   LifeSupportRegistration_PGE_CAN               30725 non-null  category
 16   LifeSupportMechanismRegistration_OTHER_CAN    30725 non-null  category
 17   VentricularDeviceTypeRegistration_CAN         30725 non-null  category
 18   VentricularDeviceBrandRegistration_CAN        30725 non-null  category
 19   FunctionalStatusRegistration_CAN              30725 non-null  category
 20   PrimaryPaymentRegistration_CAN                30725 non-null  category
 21   DiagnosisAtListing_CAN                        30725 non-null  category
 22   DiabetesType_CAN                              30725 non-null  category
 23   DialysisTypeRegistration_CAN                  30725 non-null  category
 24   CerebroVascularDisease_CAN                    30725 non-null  category
 25   PreviousMalignancy_CAN                        30725 non-null  category
 26   CreatinineRegistration_CAN                    30569 non-null  float64
 27   TotalSerumAlbuminRegistration_CAN             10073 non-null  float64
 28   DefibrillatorImplantRegistration_CAN          30725 non-null  category
 29   HemodynamicsRegistration_SYS_CAN              29613 non-null  float64
 30   HemodynamicsRegistration_PA_DIA_CAN           29591 non-null  float64
 31   HemodynamicsRegistration_PA_MN_CAN            29274 non-null  float64
 32   HemodynamicsRegistration_PCW_CAN              27801 non-null  float64
 33   HemodynamicsRegistration_CO_CAN               28924 non-null  float64
 34   InotropesVasodilatorsRegistration_SYS_CAN     30725 non-null  category
 35   InotropesVasodilatorsRegistration_DIA_CAN     30725 non-null  category
 36   InotropesVasodilatorsRegistration_MN_CAN      30725 non-null  category
 37   InotropesVasodilatorsRegistration_PCW_CAN     30725 non-null  category
 38   InotropesVasodilatorsRegistration_CO_CAN      30725 non-null  category
 39   CigaretteUse_CAN                              30725 non-null  category
 40   CigaretteAbstinence_CAN                       30725 non-null  category
 41   PriorCardiacSurgery_CAN                       30725 non-null  category
 42   PriorCardiacSurgeryType_CAN                   30725 non-null  category
 43   PriorCardiacSurgeryTypeText_CAN               6318 non-null   category
 44   DAYS_STAT1                                    30725 non-null  object
 45   StatusDays_1A                                 30725 non-null  object
 46   StatusDays_2                                  30725 non-null  object
 47   StatusDays_1B                                 30725 non-null  object
 48   StatusDays_A4                                 30725 non-null  object
 49   StatusDays_A5                                 30725 non-null  object
 50   StatusDays_A2                                 30725 non-null  object
 51   StatusDays_A3                                 30725 non-null  object
 52   StatusDays_1                                  30725 non-null  object
 53   StatusDays_A6                                 30725 non-null  object
 54   LastInactiveStatusReason                      8042 non-null   category
 55   InitialWaitingListStatusCode_CAN              30725 non-null  category
 56   ReasonRemovalWaitingList_CAN                  30725 non-null  category
 57   ReceivedDeceasedDonorTramsplant_CAN           30725 non-null  object
 58   TotalDayWaitList_CAN                          30725 non-null  float64
 59   StatusAtTransplant_CAN                        30725 non-null  category
 60   Age_Listing_CAN                               30725 non-null  int64
 61   LifeSupportRegistration_CAN                   30725 non-null  category
 62   AllocationBeginDate_CAN                       30725 non-null  datetime64[ns]
 63   RemovalWaitListDate_CAN                       30725 non-null  datetime64[ns]
 64   InitialWaitListDate_CAN                       30725 non-null  datetime64[ns]
 65   Hispanic_CAN                                  30725 non-null  category
 66   Ethnicity_CAN                                 30725 non-null  category
 67   Height_cm_Listing_CAN                         30724 non-null  float64
 68   Weight_kg_Listing_CAN                         30703 non-null  float64
 69   BMI_Listing_CALC_CAN                          30682 non-null  float64
 70   Height_cm_Removal_CAN                         30725 non-null  float64
 71   Weight_kg_Removal_CAN                         30718 non-null  float64
 72   BMI_Removal_CAN                               30712 non-null  float64
 73   COMPOSITE_DEATH_DATE                          30725 non-null  object
 74   VentilatorRegistration_CAN                    30725 non-null  category
 75   TransplantRegion_CAN                          30725 non-null  category
 76   ValidationDateTCR_CAN                         22964 non-null  datetime64[ns]
 77   WorkIncomeRegistration_CAN                    30725 non-null  category
 78   AntigenBW4_CAN                                30725 non-null  category
 79   AntigenBW6_CAN                                30725 non-null  category
 80   AntigenC1_CAN                                 30725 non-null  category
 81   AntigenC2_CAN                                 30725 non-null  category
 82   AntigenDR51_CAN                               30725 non-null  category
 83   AntigenDR51_2_CAN                             30725 non-null  category
 84   AntigenDR52_CAN                               30725 non-null  category
 85   AntigenDR52_2_CAN                             30725 non-null  category
 86   AntigenDR53_CAN                               30725 non-null  category
 87   AntigenDR53_2_CAN                             30725 non-null  category
 88   AntigenDQ1_CAN                                30725 non-null  category
 89   AntigenDQ2_CAN                                30725 non-null  category
 90   FunctionalStatusTransplant_CAN                30725 non-null  category
 91   MedicalConditionTransplant_CAN                30725 non-null  category
 92   STATUS_TRR                                    30725 non-null  object
 93   AdmissionDate_CAN                             30344 non-null  datetime64[ns]
 94   PrimaryPaymentTransplant_CAN                  30725 non-null  category
 95   LifeSupportTransplant_ECMO_CAN                30725 non-null  category
 96   ResidencyStateTransplant_CAN                  30725 non-null  category
 97   WorkIncomeTransplant_CAN                      30725 non-null  category
 98   LifeSupportTransplant_PGE_CAN                 30725 non-null  category
 99   CreatinineTransplant_CAN                      30304 non-null  float64
 100  DialysisBetweenRegistrationTransplant_CAN     30725 non-null  category
 101  HemodynamicsTransplant_CO_CAN                 28985 non-null  float64
 102  HemodynamicsTransplant_PA_DIA_CAN             29473 non-null  float64
 103  HemodynamicsTransplant_PA_MN_CAN              29174 non-null  float64
 104  HemodynamicsTransplant_PCW_CAN                28124 non-null  float64
 105  HemodynamicsTransplant_SYS_CAN                29497 non-null  float64
 106  LifeSupportTransplant_IABP_CAN                30725 non-null  category
 107  InfectionTherapyIV_CAN                        30725 non-null  category
 108  InotropesIVTransplant_CAN                     30725 non-null  category
 109  InotropesVasodilatorsTransplant_CO_CAN        30725 non-null  category
 110  InotropesVasodilatorsTransplant_DIA_CAN       30725 non-null  category
 111  InotropesVasodilatorsTransplant_MN_CAN        30725 non-null  category
 112  InotropesVasodilatorsTransplant_PCW_CAN       30725 non-null  category
 113  InotropesVasodilatorsTransplant_SYS_CAN       30725 non-null  category
 114  LifeSupportMechanismTransplant_OTHER_CAN      30725 non-null  category
 115  PriorLungSurgeryAfterRegistration_CAN         30725 non-null  category
 116  AirwayDehiscencePostTransplant                30725 non-null  category
 117  AcuteRejectionEpisode                         30725 non-null  category
 118  StrokePostTransplant                          30725 non-null  category
 119  DialysisPostDischarge                         30725 non-null  category
 120  PacemakerPostTransplant                       30725 non-null  category
 121  SteroidsUse_CAN                               30725 non-null  category
 122  TotalBilirubinTransplant_CAN                  30241 non-null  float64
 123  TransfusionAfterRegistration_CAN              30725 non-null  category
 124  VentricularDeviceTypeTransplant_CAN           30725 non-null  category
 125  VentricularDeviceBrandTransplant_CAN          30725 non-null  category
 126  VentilatorySupport_CAN                        30725 non-null  category
 127  VentilatorTransplant_CAN                      30725 non-null  category
 128  LifeSupportInhaledTransplant_CAN              30725 non-null  category
 129  PriorCardiacSurgeryTypeListAndTransplant_CAN  30725 non-null  category
 130  Hepatitis_B_CoreAntibody_CAN                  30725 non-null  category
 131  SurfaceAntigenHEP_B_CAN                       30725 non-null  category
 132  SurfaceHBVAntibodyTotalTransplant_CAN         30725 non-null  category
 133  CMVStatus_Transplant_CAN                      30725 non-null  category
 134  HIV_SeroStatusTransplant_CAN                  30725 non-null  category
 135  HEP_C_SerostatusStatus_CAN                    30725 non-null  category
 136  EpsteinBarrSeroStatusTransplant_CAN           30725 non-null  category
 137  HIV_NAT_PreTransplant_CAN                     30725 non-null  category
 138  HCV_NAT_PreTranspant_CAN                      30725 non-null  category
 139  HBV_NAT_Result_CAN                            30725 non-null  category
 140  COD                                           30725 non-null  object
 141  GraftFailStatus                               30725 non-null  category
 142  GraftLifeSpanDay                              30299 non-null  float64
 143  LastFollowupNumber                            30725 non-null  object
 144  TransplantStatus                              30725 non-null  category
 145  TransplantSurvivalDay                         30300 non-null  float64
 146  RecipientStatus                               30725 non-null  category
 147  FunctionalStatusFollowUp                      30725 non-null  category
 148  TXHRT                                         30725 non-null  category
 149  TransplantProcedure_CAN                       30725 non-null  category
 150  STATUS_TCR                                    30725 non-null  object
 151  LifeSupportInhaledRegistration_CAN            30725 non-null  category
 152  DeceasedRetyped_DON                           30725 non-null  category
 153  CrossMatchDone                                30725 non-null  category
 154  CPRA_Recent_CAN                               15524 non-null  float64
 155  CPRA_Peak_CAN                                 15512 non-null  float64
 156  RejectionTreatmentWithinOneYear               30725 non-null  category
 157  PreviousTransplantSameOrgan_CAN               30725 non-null  category
 158  PreviousTransplantAnyOrgan_CAN                30725 non-null  category
 159  AntigenDA1_DON                                30725 non-null  category
 160  AntigenDA2_DON                                30725 non-null  category
 161  AntigenDB1_DON                                30725 non-null  category
 162  AntigenDB2_DON                                30725 non-null  category
 163  AntigenDDR1_DON                               30725 non-null  category
 164  AntigenDDR2_DON                               30725 non-null  category
 165  AntigenRA1_CAN                                30725 non-null  category
 166  AntigenRA2_CAN                                30725 non-null  category
 167  AntigenRB1_CAN                                30725 non-null  category
 168  AntigenRB2_CAN                                30725 non-null  category
 169  AntigenRDR1_CAN                               30725 non-null  category
 170  AntigenRDR2_CAN                               30725 non-null  category
 171  MismatchLevel_AMIS                            30725 non-null  category
 172  MismatchLevel_BMIS                            30725 non-null  category
 173  MismatchLevel_DRMIS                           30725 non-null  category
 174  MismatchLevel_HLAMIS                          30725 non-null  category
 175  Class1PRA_TransplantPercentage_CAN            10035 non-null  float64
 176  Class2PRA_TransplantPercentage_CAN            9830 non-null   float64
 177  MalignancyBetweenRegistrationTransplant_CAN   30725 non-null  category
 178  CMV_IGG_Transplant_CAN                        30725 non-null  category
 179  CMV_IGM_Transplant_CAN                        30725 non-null  category
 180  Citizenship_DON                               30725 non-null  category
 181  PastCocaineUse_DON                            30725 non-null  category
 182  Age_DON                                       30725 non-null  int64
 183  Ethnicity_DON                                 30725 non-null  category
 184  Hepatitis_B_CoreAntibody_DON                  30725 non-null  category
 185  SurfaceAntigenHEP_B_DON                       30725 non-null  category
 186  BloodGroup_DON                                30725 non-null  category
 187  HeavyAlcoholUse_DON                           30725 non-null  category
 188  DeceasedOrLiving_DON                          30725 non-null  category
 189  Gender_DON                                    30725 non-null  category
 190  ResidencyState_DON                            30725 non-null  category
 191  Antibody_HEP_C_DON                            30725 non-null  category
 192  NonHeartBeating_DON                           30725 non-null  category
 193  AntiHypertensive_DON                          30725 non-null  category
 194  BloodInfectionSource_DON                      30725 non-null  category
 195  BloodUreaNitrogenLevel_DON                    30518 non-null  float64
 196  Creatinine_DON                                30518 non-null  float64
 197  OtherInfectionSource_DON                      30725 non-null  category
 198  Diuretics_DON                                 30725 non-null  category
 199  SteroidsUse_DON                               30725 non-null  category
 200  TriiodothyronineT3_DON                        30725 non-null  category
 201  ThyroxineT4_DON                               30725 non-null  category
 202  OtherMedsText2_DON                            26425 non-null  object
 203  OtherMedsText3_DON                            17962 non-null  object
 204  OtherMedsText1_DON                            29814 non-null  object
 205  PulmonaryInfection_DON                        30725 non-null  category
 206  PULM_INF_CONF_DON                             30725 non-null  category
 207  Level_SGOT_AST_DON                            30514 non-null  float64
 208  Level_SGOT_ALT_DON                            30514 non-null  float64
 209  TerminalTotalBilirubin_DON                    30515 non-null  float64
 210  UrineInfection_DON                            30725 non-null  category
 211  Vasodilators_DON                              30725 non-null  category
 212  AntibodyResultRPR_VDRL_DON                    30725 non-null  category
 213  InfectionClinical_DON                         30725 non-null  category
 214  CocaineUse_DON                                30725 non-null  category
 215  OtherDrugUse_DON                              30725 non-null  category
 216  CancerExtraCranial_DON                        30725 non-null  category
 217  CancerSite_DON                                30725 non-null  category
 218  CigaretteHistory_DON                          30725 non-null  category
 219  HypertensionHistory_DON                       30725 non-null  category
 220  CancerIntraCranial_DON                        30725 non-null  category
 221  CancerHistory_DON                             30725 non-null  category
 222  DiabetesHistory_DON                           30725 non-null  category
 223  Diabetes_DON                                  30725 non-null  category
 224  PastOtherDrugUse_DON                          30725 non-null  category
 225  CancerSkin_DON                                30725 non-null  category
 226  SerologyAntiCMV_DON                           30725 non-null  category
 227  CauseOfDeath_DON                              30725 non-null  category
 228  SyntheticAntiDiureticHormone_DON              30725 non-null  category
 229  DeathCircumstance_DON                         30725 non-null  category
 230  DeathMechanism_DON                            30725 non-null  category
 231  OrganRecoveryDate_DON                         30712 non-null  datetime64[ns]
 232  HeparinManagement_DON                         30725 non-null  category
 233  ArginnieManagement_DON                        30725 non-null  category
 234  InsulinManagement_DON                         30725 non-null  category
 235  Height_cm_DON                                 30725 non-null  float64
 236  Weight_kg_DON                                 30721 non-null  float64
 237  BMI_Donation_DON                              30715 non-null  float64
 238  HBV_NAT_Result_DON                            30725 non-null  category
 239  HCV_NAT_Result_DON                            30725 non-null  category
 240  HIV_NAT_Result_DON                            30725 non-null  category
 241  StatusDate_CAN                                30299 non-null  datetime64[ns]
 242  TransplantDate_CAN                            30725 non-null  datetime64[ns]
 243  CenterDischargeDate_CAN                       29880 non-null  datetime64[ns]
 244  TransplantType_CAN                            30725 non-null  category
 245  BloodGroupMatchLevel                          30725 non-null  category
 246  Age_CAN                                       30725 non-null  int64
 247  PrimaryDiagnosisType_CAN                      30725 non-null  category
 248  DialysisPriorRegistration_CAN                 30725 non-null  category
 249  IschemicTimeHour_DON                          30133 non-null  float64
 250  GraftStatus                                   30725 non-null  category
 251  AllocationType_DON                            30725 non-null  category
 252  LengthOfStay                                  29790 non-null  float64
 253  LifeSupportTransplant_CAN                     30725 non-null  category
 254  PriorCardiacSurgeryListAndTransplant_CAN      30725 non-null  category
 255  Malignancy_CAN                                30725 non-null  category

In [5]:
df_dict.info(max_cols=df_dict.shape[1])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306 entries, 0 to 305
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Feature            306 non-null    object
 1   Description        306 non-null    object
 2   Form               304 non-null    object
 3   FeatureStartDate   244 non-null    datetime64[ns]
 4   FeatureEndDate     9 non-null      datetime64[ns]
 5   FormSection        306 non-null    object
 6   DataType           306 non-null    object
 7   SASAnalysisFormat  306 non-null    object
 8   Comment            306 non-null    object
 9   OrginalFeature     306 non-null    object
 10  FeatureType        306 non-null    object
 11  Information        306 non-null    object
dtypes: datetime64[ns](2), object(10)
memory usage: 28.8+ KB

## Data Wrangle (Complete Data)

#### User Function(s)

In [6]:
def get_cols_by_cardinality(data, cat, dropna=True, flag=False):
    if flag:
        # return columns with cardinality > cat
        return [
            col for col in data.columns
            if data[col].nunique(dropna=dropna) > cat
        ]
    else:
        # return columns with cardinality <= cat
        return [
            col for col in data.columns
            if data[col].nunique(dropna=dropna) <= cat
        ]


def get_column_summary(data, cat=2, flag=True, dropna=True, ignore_list=None):
    """
    Categorizes columns based on unique value counts.
    
    Args:
        data: DataFrame to analyze.
        cat: The threshold for the number of unique values.
        flag: If True, finds columns > cat. If False, finds columns <= cat.
        dropna: Whether to count NaNs as a unique value.
        ignore_list: List of column names to exclude from the result.
    """
    if ignore_list is None:
        ignore_list = []

    # Identify columns based on the 'cat' threshold
    if flag:
        cols = [col for col in data.columns if data[col].nunique(dropna=dropna) > cat]
    else:
        cols = [col for col in data.columns if data[col].nunique(dropna=dropna) <= cat]

    # Efficiently remove ignored columns
    cols = [col for col in cols if col not in ignore_list]
    
    # Create a dictionary of unique values
    summary = {col: data[col].unique().tolist() for col in cols}
    
    print(f"--- Found {len(cols)} Columns (Threshold: {'>' if flag else '<='} {cat}) ---")
    
    # Truncate long lists for cleaner printing
    for key, value in summary.items():
        val_str = f"{value[:5]}..." if len(value) > 5 else f"{value}"
        print(f"{key} : {val_str}")

    return list(summary.keys())

In [7]:
# remove cols
remove_cols = ['DAYS_STAT1',
 'StatusDays_1A',
 'StatusDays_1B',
 'StatusDays_2',
 'StatusDays_1',
 'StatusDays_A2',
 'StatusDays_A3',
 'StatusDays_A4',
 'StatusDays_A5',
 'StatusDays_A6',
 'LastInactiveStatusReason',
 'ReasonRemovalWaitingList_CAN',
 'STATUS_TRR',
 'STATUS_TCR',
 'STATUS_DDR',
 'AcuteRejectionEpisode',
 'AirwayDehiscencePostTransplant',
 'StrokePostTransplant',
 'PacemakerPostTransplant',
 'DialysisPostDischarge',
 'GraftFailStatus',
 'GraftLifeSpanDay',
 'LastFollowupNumber',
 'GraftStatus',
 'TransplantStatus',
 'RecipientStatus',
 'RejectionTreatmentWithinOneYear',
 'FunctionalStatusFollowUp',
 'LengthOfStay']
# remove unwanted features
df = df.drop(columns=remove_cols).copy()

In [8]:
df.info(max_cols=df.shape[1])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30725 entries, 0 to 30724
Data columns (total 266 columns):
 #    Column                                        Non-Null Count  Dtype
---   ------                                        --------------  -----
 0    PreviousTransplantNumber_CAN                  30725 non-null  category
 1    WaitListDiagnosisCode_CAN                     30725 non-null  category
 2    INUTERO                                       6319 non-null   object
 3    Gender_CAN                                    30725 non-null  category
 4    BloodGroup_CAN                                30725 non-null  category
 5    Weight_kg_Registrsation_CAN                   30673 non-null  float64
 6    Height_cm_Registration_CAN                    30608 non-null  float64
 7    BMI_Listing_CAN                               30606 non-null  float64
 8    Citizenship_CAN                               30725 non-null  category
 9    ResidencyStateRegistration_CAN                30725 non-null  category
 10   EducationLevel_CAN                            30725 non-null  category
 11   LifeSupportRegistration_ECMO_CAN              30725 non-null  category
 12   LifeSupportRegistration_IABP_CAN              30725 non-null  category
 13   LifeSupportInhaled_CAN                        30725 non-null  category
 14   InotropesIVRegistration_CAN                   30725 non-null  category
 15   LifeSupportRegistration_PGE_CAN               30725 non-null  category
 16   LifeSupportMechanismRegistration_OTHER_CAN    30725 non-null  category
 17   VentricularDeviceTypeRegistration_CAN         30725 non-null  category
 18   VentricularDeviceBrandRegistration_CAN        30725 non-null  category
 19   FunctionalStatusRegistration_CAN              30725 non-null  category
 20   PrimaryPaymentRegistration_CAN                30725 non-null  category
 21   DiagnosisAtListing_CAN                        30725 non-null  category
 22   DiabetesType_CAN                              30725 non-null  category
 23   DialysisTypeRegistration_CAN                  30725 non-null  category
 24   CerebroVascularDisease_CAN                    30725 non-null  category
 25   PreviousMalignancy_CAN                        30725 non-null  category
 26   CreatinineRegistration_CAN                    30569 non-null  float64
 27   TotalSerumAlbuminRegistration_CAN             10073 non-null  float64
 28   DefibrillatorImplantRegistration_CAN          30725 non-null  category
 29   HemodynamicsRegistration_SYS_CAN              29613 non-null  float64
 30   HemodynamicsRegistration_PA_DIA_CAN           29591 non-null  float64
 31   HemodynamicsRegistration_PA_MN_CAN            29274 non-null  float64
 32   HemodynamicsRegistration_PCW_CAN              27801 non-null  float64
 33   HemodynamicsRegistration_CO_CAN               28924 non-null  float64
 34   InotropesVasodilatorsRegistration_SYS_CAN     30725 non-null  category
 35   InotropesVasodilatorsRegistration_DIA_CAN     30725 non-null  category
 36   InotropesVasodilatorsRegistration_MN_CAN      30725 non-null  category
 37   InotropesVasodilatorsRegistration_PCW_CAN     30725 non-null  category
 38   InotropesVasodilatorsRegistration_CO_CAN      30725 non-null  category
 39   CigaretteUse_CAN                              30725 non-null  category
 40   CigaretteAbstinence_CAN                       30725 non-null  category
 41   PriorCardiacSurgery_CAN                       30725 non-null  category
 42   PriorCardiacSurgeryType_CAN                   30725 non-null  category
 43   PriorCardiacSurgeryTypeText_CAN               6318 non-null   category
 44   InitialWaitingListStatusCode_CAN              30725 non-null  category
 45   ReceivedDeceasedDonorTramsplant_CAN           30725 non-null  object
 46   TotalDayWaitList_CAN                          30725 non-null  float64
 47   StatusAtTransplant_CAN                        30725 non-null  category
 48   Age_Listing_CAN                               30725 non-null  int64
 49   LifeSupportRegistration_CAN                   30725 non-null  category
 50   AllocationBeginDate_CAN                       30725 non-null  datetime64[ns]
 51   RemovalWaitListDate_CAN                       30725 non-null  datetime64[ns]
 52   InitialWaitListDate_CAN                       30725 non-null  datetime64[ns]
 53   Hispanic_CAN                                  30725 non-null  category
 54   Ethnicity_CAN                                 30725 non-null  category
 55   Height_cm_Listing_CAN                         30724 non-null  float64
 56   Weight_kg_Listing_CAN                         30703 non-null  float64
 57   BMI_Listing_CALC_CAN                          30682 non-null  float64
 58   Height_cm_Removal_CAN                         30725 non-null  float64
 59   Weight_kg_Removal_CAN                         30718 non-null  float64
 60   BMI_Removal_CAN                               30712 non-null  float64
 61   COMPOSITE_DEATH_DATE                          30725 non-null  object
 62   VentilatorRegistration_CAN                    30725 non-null  category
 63   TransplantRegion_CAN                          30725 non-null  category
 64   ValidationDateTCR_CAN                         22964 non-null  datetime64[ns]
 65   WorkIncomeRegistration_CAN                    30725 non-null  category
 66   AntigenBW4_CAN                                30725 non-null  category
 67   AntigenBW6_CAN                                30725 non-null  category
 68   AntigenC1_CAN                                 30725 non-null  category
 69   AntigenC2_CAN                                 30725 non-null  category
 70   AntigenDR51_CAN                               30725 non-null  category
 71   AntigenDR51_2_CAN                             30725 non-null  category
 72   AntigenDR52_CAN                               30725 non-null  category
 73   AntigenDR52_2_CAN                             30725 non-null  category
 74   AntigenDR53_CAN                               30725 non-null  category
 75   AntigenDR53_2_CAN                             30725 non-null  category
 76   AntigenDQ1_CAN                                30725 non-null  category
 77   AntigenDQ2_CAN                                30725 non-null  category
 78   FunctionalStatusTransplant_CAN                30725 non-null  category
 79   MedicalConditionTransplant_CAN                30725 non-null  category
 80   AdmissionDate_CAN                             30344 non-null  datetime64[ns]
 81   PrimaryPaymentTransplant_CAN                  30725 non-null  category
 82   LifeSupportTransplant_ECMO_CAN                30725 non-null  category
 83   ResidencyStateTransplant_CAN                  30725 non-null  category
 84   WorkIncomeTransplant_CAN                      30725 non-null  category
 85   LifeSupportTransplant_PGE_CAN                 30725 non-null  category
 86   CreatinineTransplant_CAN                      30304 non-null  float64
 87   DialysisBetweenRegistrationTransplant_CAN     30725 non-null  category
 88   HemodynamicsTransplant_CO_CAN                 28985 non-null  float64
 89   HemodynamicsTransplant_PA_DIA_CAN             29473 non-null  float64
 90   HemodynamicsTransplant_PA_MN_CAN              29174 non-null  float64
 91   HemodynamicsTransplant_PCW_CAN                28124 non-null  float64
 92   HemodynamicsTransplant_SYS_CAN                29497 non-null  float64
 93   LifeSupportTransplant_IABP_CAN                30725 non-null  category
 94   InfectionTherapyIV_CAN                        30725 non-null  category
 95   InotropesIVTransplant_CAN                     30725 non-null  category
 96   InotropesVasodilatorsTransplant_CO_CAN        30725 non-null  category
 97   InotropesVasodilatorsTransplant_DIA_CAN       30725 non-null  category
 98   InotropesVasodilatorsTransplant_MN_CAN        30725 non-null  category
 99   InotropesVasodilatorsTransplant_PCW_CAN       30725 non-null  category
 100  InotropesVasodilatorsTransplant_SYS_CAN       30725 non-null  category
 101  LifeSupportMechanismTransplant_OTHER_CAN      30725 non-null  category
 102  PriorLungSurgeryAfterRegistration_CAN         30725 non-null  category
 103  SteroidsUse_CAN                               30725 non-null  category
 104  TotalBilirubinTransplant_CAN                  30241 non-null  float64
 105  TransfusionAfterRegistration_CAN              30725 non-null  category
 106  VentricularDeviceTypeTransplant_CAN           30725 non-null  category
 107  VentricularDeviceBrandTransplant_CAN          30725 non-null  category
 108  VentilatorySupport_CAN                        30725 non-null  category
 109  VentilatorTransplant_CAN                      30725 non-null  category
 110  LifeSupportInhaledTransplant_CAN              30725 non-null  category
 111  PriorCardiacSurgeryTypeListAndTransplant_CAN  30725 non-null  category
 112  Hepatitis_B_CoreAntibody_CAN                  30725 non-null  category
 113  SurfaceAntigenHEP_B_CAN                       30725 non-null  category
 114  SurfaceHBVAntibodyTotalTransplant_CAN         30725 non-null  category
 115  CMVStatus_Transplant_CAN                      30725 non-null  category
 116  HIV_SeroStatusTransplant_CAN                  30725 non-null  category
 117  HEP_C_SerostatusStatus_CAN                    30725 non-null  category
 118  EpsteinBarrSeroStatusTransplant_CAN           30725 non-null  category
 119  HIV_NAT_PreTransplant_CAN                     30725 non-null  category
 120  HCV_NAT_PreTranspant_CAN                      30725 non-null  category
 121  HBV_NAT_Result_CAN                            30725 non-null  category
 122  COD                                           30725 non-null  object
 123  TransplantSurvivalDay                         30300 non-null  float64
 124  TXHRT                                         30725 non-null  category
 125  TransplantProcedure_CAN                       30725 non-null  category
 126  LifeSupportInhaledRegistration_CAN            30725 non-null  category
 127  DeceasedRetyped_DON                           30725 non-null  category
 128  CrossMatchDone                                30725 non-null  category
 129  CPRA_Recent_CAN                               15524 non-null  float64
 130  CPRA_Peak_CAN                                 15512 non-null  float64
 131  PreviousTransplantSameOrgan_CAN               30725 non-null  category
 132  PreviousTransplantAnyOrgan_CAN                30725 non-null  category
 133  AntigenDA1_DON                                30725 non-null  category
 134  AntigenDA2_DON                                30725 non-null  category
 135  AntigenDB1_DON                                30725 non-null  category
 136  AntigenDB2_DON                                30725 non-null  category
 137  AntigenDDR1_DON                               30725 non-null  category
 138  AntigenDDR2_DON                               30725 non-null  category
 139  AntigenRA1_CAN                                30725 non-null  category
 140  AntigenRA2_CAN                                30725 non-null  category
 141  AntigenRB1_CAN                                30725 non-null  category
 142  AntigenRB2_CAN                                30725 non-null  category
 143  AntigenRDR1_CAN                               30725 non-null  category
 144  AntigenRDR2_CAN                               30725 non-null  category
 145  MismatchLevel_AMIS                            30725 non-null  category
 146  MismatchLevel_BMIS                            30725 non-null  category
 147  MismatchLevel_DRMIS                           30725 non-null  category
 148  MismatchLevel_HLAMIS                          30725 non-null  category
 149  Class1PRA_TransplantPercentage_CAN            10035 non-null  float64
 150  Class2PRA_TransplantPercentage_CAN            9830 non-null   float64
 151  MalignancyBetweenRegistrationTransplant_CAN   30725 non-null  category
 152  CMV_IGG_Transplant_CAN                        30725 non-null  category
 153  CMV_IGM_Transplant_CAN                        30725 non-null  category
 154  Citizenship_DON                               30725 non-null  category
 155  PastCocaineUse_DON                            30725 non-null  category
 156  Age_DON                                       30725 non-null  int64
 157  Ethnicity_DON                                 30725 non-null  category
 158  Hepatitis_B_CoreAntibody_DON                  30725 non-null  category
 159  SurfaceAntigenHEP_B_DON                       30725 non-null  category
 160  BloodGroup_DON                                30725 non-null  category
 161  HeavyAlcoholUse_DON                           30725 non-null  category
 162  DeceasedOrLiving_DON                          30725 non-null  category
 163  Gender_DON                                    30725 non-null  category
 164  ResidencyState_DON                            30725 non-null  category
 165  Antibody_HEP_C_DON                            30725 non-null  category
 166  NonHeartBeating_DON                           30725 non-null  category
 167  AntiHypertensive_DON                          30725 non-null  category
 168  BloodInfectionSource_DON                      30725 non-null  category
 169  BloodUreaNitrogenLevel_DON                    30518 non-null  float64
 170  Creatinine_DON                                30518 non-null  float64
 171  OtherInfectionSource_DON                      30725 non-null  category
 172  Diuretics_DON                                 30725 non-null  category
 173  SteroidsUse_DON                               30725 non-null  category
 174  TriiodothyronineT3_DON                        30725 non-null  category
 175  ThyroxineT4_DON                               30725 non-null  category
 176  OtherMedsText2_DON                            26425 non-null  object
 177  OtherMedsText3_DON                            17962 non-null  object
 178  OtherMedsText1_DON                            29814 non-null  object
 179  PulmonaryInfection_DON                        30725 non-null  category
 180  PULM_INF_CONF_DON                             30725 non-null  category
 181  Level_SGOT_AST_DON                            30514 non-null  float64
 182  Level_SGOT_ALT_DON                            30514 non-null  float64
 183  TerminalTotalBilirubin_DON                    30515 non-null  float64
 184  UrineInfection_DON                            30725 non-null  category
 185  Vasodilators_DON                              30725 non-null  category
 186  AntibodyResultRPR_VDRL_DON                    30725 non-null  category
 187  InfectionClinical_DON                         30725 non-null  category
 188  CocaineUse_DON                                30725 non-null  category
 189  OtherDrugUse_DON                              30725 non-null  category
 190  CancerExtraCranial_DON                        30725 non-null  category
 191  CancerSite_DON                                30725 non-null  category
 192  CigaretteHistory_DON                          30725 non-null  category
 193  HypertensionHistory_DON                       30725 non-null  category
 194  CancerIntraCranial_DON                        30725 non-null  category
 195  CancerHistory_DON                             30725 non-null  category
 196  DiabetesHistory_DON                           30725 non-null  category
 197  Diabetes_DON                                  30725 non-null  category
 198  PastOtherDrugUse_DON                          30725 non-null  category
 199  CancerSkin_DON                                30725 non-null  category
 200  SerologyAntiCMV_DON                           30725 non-null  category
 201  CauseOfDeath_DON                              30725 non-null  category
 202  SyntheticAntiDiureticHormone_DON              30725 non-null  category
 203  DeathCircumstance_DON                         30725 non-null  category
 204  DeathMechanism_DON                            30725 non-null  category
 205  OrganRecoveryDate_DON                         30712 non-null  datetime64[ns]
 206  HeparinManagement_DON                         30725 non-null  category
 207  ArginnieManagement_DON                        30725 non-null  category
 208  InsulinManagement_DON                         30725 non-null  category
 209  Height_cm_DON                                 30725 non-null  float64
 210  Weight_kg_DON                                 30721 non-null  float64
 211  BMI_Donation_DON                              30715 non-null  float64
 212  HBV_NAT_Result_DON                            30725 non-null  category
 213  HCV_NAT_Result_DON                            30725 non-null  category
 214  HIV_NAT_Result_DON                            30725 non-null  category
 215  StatusDate_CAN                                30299 non-null  datetime64[ns]
 216  TransplantDate_CAN                            30725 non-null  datetime64[ns]
 217  CenterDischargeDate_CAN                       29880 non-null  datetime64[ns]
 218  TransplantType_CAN                            30725 non-null  category
 219  BloodGroupMatchLevel                          30725 non-null  category
 220  Age_CAN                                       30725 non-null  int64
 221  PrimaryDiagnosisType_CAN                      30725 non-null  category
 222  DialysisPriorRegistration_CAN                 30725 non-null  category
 223  IschemicTimeHour_DON                          30133 non-null  float64
 224  AllocationType_DON                            30725 non-null  category
 225  LifeSupportTransplant_CAN                     30725 non-null  category
 226  PriorCardiacSurgeryListAndTransplant_CAN      30725 non-null  category
 227  Malignancy_CAN                                30725 non-null  category
 228  Height_cm_CAN                                 30725 non-null  float64
 229  Weight_kg_CAN                                 30718 non-null  float64
 230  BMI_Calc_CAN                                  30712 non-null  float64
 231  DistanceFromDonorHospitaltoTXCenter_CAN       30725 non-null  float64
 232  VentilatorySupportAfterRegistration_CAN       30725 non-null  category
 233  HeartProcedureType_CAN                        30725 non-null  category
 234  ValidationDateTRR_CAN                         30223 non-null  datetime64[ns]
 235  AdmissionDate_DON                             30688 non-null  datetime64[ns]
 236  UrineProtein_DON                              30725 non-null  category
 237  CardiacArrest_DON                             30725 non-null  category
 238  LungPO2_DON                                   30463 non-null  float64
 239  MyocardialInfarctionHistory_DON               30725 non-null  category
 240  LV_EjectionFractionMedthod_DON                30725 non-null  category
 241  LV_EjectionFractionPercent_DON                30689 non-null  float64
 242  CoronaryAngiogram_DON                         30725 non-null  category
 243  Biopsy_DON                                    30725 non-null  category
 244  Tatoos_DON                                    30725 non-null  category
 245  ValidationDateTCR_DDR                         30495 non-null  datetime64[ns]
 246  AntibodyResultHBSAB_DON                       30725 non-null  category
 247  EpsteinBarr_IGG_DON                           30725 non-null  category
 248  EpsteinBarr_IGM_DON                           30725 non-null  category
 249  HIV_Risk_DON                                  30725 non-null  category
 250  InotropicAgent_DON                            30725 non-null  category
 251  KidneyAllocation_DON                          30725 non-null  category
 252  TransplantYear_CAN                            30725 non-null  category
 253  InotropicMedicationProcurement_DON            30725 non-null  category
 254  ReferralDate_DON                              30708 non-null  datetime64[ns]
 255  ListingYear_CAN                               30725 non-null  int64

* **TCR:** Transplant Candidate Registration
* **TRR:** Transplant Recipient Registration

In [9]:
u.any_nans(df)

--- Missing Values Found () (Total Rows: 30,725) ---
                                     Count Percentage
PriorCardiacSurgeryTypeText_CAN      24407   79.4369%
INUTERO                              24406   79.4337%
Class2PRA_TransplantPercentage_CAN   20895   68.0065%
Class1PRA_TransplantPercentage_CAN   20690   67.3393%
TotalSerumAlbuminRegistration_CAN    20652   67.2156%
CPRA_Peak_CAN                        15213   49.5134%
CPRA_Recent_CAN                      15201   49.4744%
OtherMedsText3_DON                   12763   41.5395%
ValidationDateTCR_CAN                 7761   25.2596%
OtherMedsText2_DON                    4300   13.9951%
HemodynamicsRegistration_PCW_CAN      2924    9.5167%
HemodynamicsTransplant_PCW_CAN        2601    8.4654%
HemodynamicsRegistration_CO_CAN       1801    5.8617%
HemodynamicsTransplant_CO_CAN         1740    5.6631%
HemodynamicsTransplant_PA_MN_CAN      1551    5.0480%
HemodynamicsRegistration_PA_MN_CAN    1451    4.7225%
HemodynamicsTransplant_PA_DIA_CAN     1252    4.0749%
HemodynamicsTransplant_SYS_CAN        1228    3.9967%
HemodynamicsRegistration_PA_DIA_CAN   1134    3.6908%
HemodynamicsRegistration_SYS_CAN      1112    3.6192%
OtherMedsText1_DON                     911    2.9650%
CenterDischargeDate_CAN                845    2.7502%
IschemicTimeHour_DON                   592    1.9268%
ValidationDateTRR_CAN                  502    1.6338%
TotalBilirubinTransplant_CAN           484    1.5753%
StatusDate_CAN                         426    1.3865%
TransplantSurvivalDay                  425    1.3832%
CreatinineTransplant_CAN               421    1.3702%
AdmissionDate_CAN                      381    1.2400%
LungPO2_FIO2_DON                       341    1.1098%
LungPO2_DON                            262    0.8527%
OrganRecovery_PCO2_DON                 237    0.7714%
BloodPH_DON                            231    0.7518%
ValidationDateTCR_DDR                  230    0.7486%
Level_SGOT_ALT_DON                     211    0.6867%
Level_SGOT_AST_DON                     211    0.6867%
TerminalTotalBilirubin_DON             210    0.6835%
BloodUreaNitrogenLevel_DON             207    0.6737%
Creatinine_DON                         207    0.6737%
Hematocrit_DON                         206    0.6705%
CreatinineRegistration_CAN             156    0.5077%
BMI_Listing_CAN                        119    0.3873%
Height_cm_Registration_CAN             117    0.3808%
Weight_kg_Registrsation_CAN             52    0.1692%
BMI_Listing_CALC_CAN                    43    0.1400%
AdmissionDate_DON                       37    0.1204%
LV_EjectionFractionPercent_DON          36    0.1172%
Weight_kg_Listing_CAN                   22    0.0716%
ReferralDate_DON                        17    0.0553%
BMI_Removal_CAN                         13    0.0423%
OrganRecoveryDate_DON                   13    0.0423%
BMI_Calc_CAN                            13    0.0423%
BMI_Donation_DON                        10    0.0325%
Weight_kg_Removal_CAN                    7    0.0228%
Weight_kg_CAN                            7    0.0228%
Weight_kg_DON                            4    0.0130%
Height_cm_Listing_CAN                    1    0.0033%

#### Features with > 40& Missingness & Dates REMOVED

In [10]:
# remove: include Hispanic_CAN & Date features (OtherMedsText3_DON keep since its part of two other fetures)
remove_cols = ['PriorCardiacSurgeryTypeText_CAN','INUTERO', 'Class2PRA_TransplantPercentage_CAN', 'Class1PRA_TransplantPercentage_CAN',
        'TotalSerumAlbuminRegistration_CAN', 'CPRA_Peak_CAN', 'CPRA_Recent_CAN', 'Hispanic_CAN']

# remove all dates
remove_cols.extend(df.columns[df.columns.str.contains('Date')].tolist())
# 
df = df.drop(columns=remove_cols).copy()
#
df.shape

(30725, 245)

In [11]:
df.head()

,PreviousTransplantNumber_CAN,WaitListDiagnosisCode_CAN,Gender_CAN,BloodGroup_CAN,Weight_kg_Registrsation_CAN,Height_cm_Registration_CAN,BMI_Listing_CAN,Citizenship_CAN,ResidencyStateRegistration_CAN,EducationLevel_CAN,LifeSupportRegistration_ECMO_CAN,LifeSupportRegistration_IABP_CAN,LifeSupportInhaled_CAN,InotropesIVRegistration_CAN,LifeSupportRegistration_PGE_CAN,LifeSupportMechanismRegistration_OTHER_CAN,VentricularDeviceTypeRegistration_CAN,VentricularDeviceBrandRegistration_CAN,FunctionalStatusRegistration_CAN,PrimaryPaymentRegistration_CAN,DiagnosisAtListing_CAN,DiabetesType_CAN,DialysisTypeRegistration_CAN,CerebroVascularDisease_CAN,PreviousMalignancy_CAN,CreatinineRegistration_CAN,DefibrillatorImplantRegistration_CAN,HemodynamicsRegistration_SYS_CAN,HemodynamicsRegistration_PA_DIA_CAN,HemodynamicsRegistration_PA_MN_CAN,HemodynamicsRegistration_PCW_CAN,HemodynamicsRegistration_CO_CAN,InotropesVasodilatorsRegistration_SYS_CAN,InotropesVasodilatorsRegistration_DIA_CAN,InotropesVasodilatorsRegistration_MN_CAN,InotropesVasodilatorsRegistration_PCW_CAN,InotropesVasodilatorsRegistration_CO_CAN,CigaretteUse_CAN,CigaretteAbstinence_CAN,PriorCardiacSurgery_CAN,PriorCardiacSurgeryType_CAN,InitialWaitingListStatusCode_CAN,ReceivedDeceasedDonorTramsplant_CAN,TotalDayWaitList_CAN,StatusAtTransplant_CAN,Age_Listing_CAN,LifeSupportRegistration_CAN,Ethnicity_CAN,Height_cm_Listing_CAN,Weight_kg_Listing_CAN,BMI_Listing_CALC_CAN,Height_cm_Removal_CAN,Weight_kg_Removal_CAN,BMI_Removal_CAN,COMPOSITE_DEATH_DATE,VentilatorRegistration_CAN,TransplantRegion_CAN,WorkIncomeRegistration_CAN,AntigenBW4_CAN,AntigenBW6_CAN,AntigenC1_CAN,AntigenC2_CAN,AntigenDR51_CAN,AntigenDR51_2_CAN,AntigenDR52_CAN,AntigenDR52_2_CAN,AntigenDR53_CAN,AntigenDR53_2_CAN,AntigenDQ1_CAN,AntigenDQ2_CAN,FunctionalStatusTransplant_CAN,MedicalConditionTransplant_CAN,PrimaryPaymentTransplant_CAN,LifeSupportTransplant_ECMO_CAN,ResidencyStateTransplant_CAN,WorkIncomeTransplant_CAN,LifeSupportTransplant_PGE_CAN,CreatinineTransplant_CAN,DialysisBetweenRegistrationTransplant_CAN,HemodynamicsTransplant_CO_CAN,HemodynamicsTransplant_PA_DIA_CAN,HemodynamicsTransplant_PA_MN_CAN,HemodynamicsTransplant_PCW_CAN,HemodynamicsTransplant_SYS_CAN,LifeSupportTransplant_IABP_CAN,InfectionTherapyIV_CAN,InotropesIVTransplant_CAN,InotropesVasodilatorsTransplant_CO_CAN,InotropesVasodilatorsTransplant_DIA_CAN,InotropesVasodilatorsTransplant_MN_CAN,InotropesVasodilatorsTransplant_PCW_CAN,InotropesVasodilatorsTransplant_SYS_CAN,LifeSupportMechanismTransplant_OTHER_CAN,PriorLungSurgeryAfterRegistration_CAN,SteroidsUse_CAN,TotalBilirubinTransplant_CAN,TransfusionAfterRegistration_CAN,VentricularDeviceTypeTransplant_CAN,VentricularDeviceBrandTransplant_CAN,VentilatorySupport_CAN,VentilatorTransplant_CAN,LifeSupportInhaledTransplant_CAN,PriorCardiacSurgeryTypeListAndTransplant_CAN,Hepatitis_B_CoreAntibody_CAN,SurfaceAntigenHEP_B_CAN,SurfaceHBVAntibodyTotalTransplant_CAN,CMVStatus_Transplant_CAN,HIV_SeroStatusTransplant_CAN,HEP_C_SerostatusStatus_CAN,EpsteinBarrSeroStatusTransplant_CAN,HIV_NAT_PreTransplant_CAN,HCV_NAT_PreTranspant_CAN,HBV_NAT_Result_CAN,COD,TransplantSurvivalDay,TXHRT,TransplantProcedure_CAN,LifeSupportInhaledRegistration_CAN,DeceasedRetyped_DON,CrossMatchDone,PreviousTransplantSameOrgan_CAN,PreviousTransplantAnyOrgan_CAN,AntigenDA1_DON,AntigenDA2_DON,AntigenDB1_DON,AntigenDB2_DON,AntigenDDR1_DON,AntigenDDR2_DON,AntigenRA1_CAN,AntigenRA2_CAN,AntigenRB1_CAN,AntigenRB2_CAN,AntigenRDR1_CAN,AntigenRDR2_CAN,MismatchLevel_AMIS,MismatchLevel_BMIS,MismatchLevel_DRMIS,MismatchLevel_HLAMIS,MalignancyBetweenRegistrationTransplant_CAN,CMV_IGG_Transplant_CAN,CMV_IGM_Transplant_CAN,Citizenship_DON,PastCocaineUse_DON,Age_DON,Ethnicity_DON,Hepatitis_B_CoreAntibody_DON,SurfaceAntigenHEP_B_DON,BloodGroup_DON,HeavyAlcoholUse_DON,DeceasedOrLiving_DON,Gender_DON,ResidencyState_DON,Antibody_HEP_C_DON,NonHeartBeating_DON,AntiHypertensive_DON,BloodInfectionSource_DON,BloodUreaNitrogenLevel_DON,Creatinine_DON,OtherInfectionSource_DON,Diuretics_DON,SteroidsUse_DON,TriiodothyronineT3_DON,ThyroxineT4_DON,OtherMedsText2_DON,OtherMedsText3_DON,OtherMedsText1_DON,PulmonaryInfection_DON,PULM_INF_CONF_DON,Level_SGOT_AST_DON,Level_SGOT_ALT_DON,TerminalTotalBilirubin_DON,UrineInfection_DON,Vasodilators_DON,AntibodyResultRPR_VDRL_DON,InfectionClinical_DON,CocaineUse_DON,OtherDrugUse_DON,CancerExtraCranial_DON,CancerSite_DON,CigaretteHistory_DON,HypertensionHistory_DON,CancerIntraCranial_DON,CancerHistory_DON,DiabetesHistory_DON,Diabetes_DON,PastOtherDrugUse_DON,CancerSkin_DON,SerologyAntiCMV_DON,CauseOfDeath_DON,SyntheticAntiDiureticHormone_DON,DeathCircumstance_DON,DeathMechanism_DON,HeparinManagement_DON,ArginnieManagement_DON,InsulinManagement_DON,Height_cm_DON,Weight_kg_DON,BMI_Donation_DON,HBV_NAT_Result_DON,HCV_NAT_Result_DON,HIV_NAT_Result_DON,TransplantType_CAN,BloodGroupMatchLevel,Age_CAN,PrimaryDiagnosisType_CAN,DialysisPriorRegistration_CAN,IschemicTimeHour_DON,AllocationType_DON,LifeSupportTransplant_CAN,PriorCardiacSurgeryListAndTransplant_CAN,Malignancy_CAN,Height_cm_CAN,Weight_kg_CAN,BMI_Calc_CAN,DistanceFromDonorHospitaltoTXCenter_CAN,VentilatorySupportAfterRegistration_CAN,HeartProcedureType_CAN,UrineProtein_DON,CardiacArrest_DON,LungPO2_DON,MyocardialInfarctionHistory_DON,LV_EjectionFractionMedthod_DON,LV_EjectionFractionPercent_DON,CoronaryAngiogram_DON,Biopsy_DON,Tatoos_DON,AntibodyResultHBSAB_DON,EpsteinBarr_IGG_DON,EpsteinBarr_IGM_DON,HIV_Risk_DON,InotropicAgent_DON,KidneyAllocation_DON,TransplantYear_CAN,InotropicMedicationProcurement_DON,ListingYear_CAN,TransfusionNumber_DON,LungPO2_Done_DON,LungPO2_FIO2_DON,OrganRecovery_PCO2_DON,PulmonaryCatheter_DON,BronchoscopyLeft_DON,BronchoscopyRight_DON,ChestXray_DON,BloodPH_DON,Hematocrit_DON
0,0,DILATED MYOPATHY: IDIOPATHIC,M,A,65.771,173.0,22.0470,US Citizen,CA,ATTENDED COLLEGE/TECHNICAL SCHOOL,No,No,No,No,No,Yes,Lvad+Rvad,CentriMag (Thoratec/Levitronix),"10% - Moribund, fatal processes progressing rapidly",Public insurance - Medicaid,DILATED MYOPATHY: IDIOPATHIC,No,No dialysis,No,No,1.3,Yes,50.0,34.0,37.0,36.0,2.50,Yes,Yes,Yes,Yes,Yes,No,Unknown,Yes,Valve Replace/Repair,HR: Status 1A,Yes,11.0,Hypoplastic Left Heart Syndrome; Atrioventricular Septal Defect; Other left Heart Valvar/Structural,45,Yes,Hispanic,172.7,65.8,22.0,172.7,65.8,22.0,2013-12-24 00:00:00,No,Region 5,No,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,"10% - Moribund, fatal processes progressing rapidly",In Intensive Care Unit,Public insurance - Medicaid,No,CA,No,No,1.00,No,NaN,NaN,NaN,NaN,NaN,No,No,No,Unknown,Unknown,Unknown,Unknown,Unknown,Yes,No,No,3.6,No,Lvad+Rvad,CentriMag (Thoratec/Levitronix),Yes,No,No,"Other, specify",Negative,Negative,Unknown,Positive,Negative,Negative,Not Done,Unknown,Unknown,Unknown,2204,329.0,Yes,501,No,No,No,No,No,2,29,44,49,4,15,24,24,35,61,4,4,2,2,1,5,No,Positive,Negative,US Citizen,No,31,Black,Negative,Negative,A,No,Deceased Donor,M,CA,Negative,No,Yes,No,18.0,1.30,No,Yes,No,No,No,"KCL,","DOPAMINE, VASOPRESSIN,","ZOSYN, VANCOMYCIN",Yes,Yes,46.0,40.0,0.4,No,No,Negative,Yes,Unknown,Unknown,No,NO,No,No,No,No,No,No,No,No,Positive,HEAD TRAUMA,Yes,HOMICIDE,GUNSHOT WOUND,Yes,No,Yes,172.7,107.0,35.867286,Unknown,Unknown,Unknown,O,Identical,45,DILATED MYOPATHY: IDIOPATHIC,No,4.9,Local,Yes,Yes,No,172.7,65.3,21.9,83.0,Yes,Orthotopic Bicaval,No,No,182.0,No,Echo,60.0,No,Biopsy not done,Yes,Not Done,Positive,Negative,No,Unknown,No,2013,No,2013,1 - 5,Yes,47.0,40.0,No,Normal,Normal,Abnormal-right,7.38,26.2
1,0,DILATED MYOPATHY: OTHER SPECIFY,M,O,72.575,185.0,21.1093,US Citizen,TX,HIGH SCHOOL (9-12) or GED,No,No,No,No,No,No,Lvad,Heartmate II,"10% - Moribund, fatal processes progressing rapidly",Public insurance - Medicare FFS (Fee for Service),DILATED MYOPATHY: VIRAL,No,No dialysis,No,No,2.3,Yes,53.0,39.0,46.0,31.0,2.10,No,No,No,No,No,No,Unknown,No,Unknown,HR: Status 1A,Yes,348.0,Transposition of the Great Arteries; Truncus Arteriosus; Congenitally Corrected Transposition (L-TGA),35,Yes,Hispanic,185.4,72.6,21.1,185.4,72.6,21.1,998,No,Region 4,No,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,90% - Able to carry on normal activity: minor symptoms of disease,Not Hospitalized,Public insurance - Medicare FFS (Fee for Service),No,TX,No,No,0.70,No,4.60,8.0,18.0,4.0,28.0,No,No,No,No,No,No,No,No,No,No,No,0.9,No,Lvad,Heartmate II,No,No,No,Unknown,Negative,Negative,Unknown,Positive,Negative,Negative,Positive,Unknown,Unknown,Unknown,998,2592.0,Yes,501,No,Yes,Yes,No,No,2,68,49,60,10,16,30,68,48,65,8,9,1,2,2,5,No,Positive,Negative,Non-US Citizen/US Resident,No,30,Hispanic,Negative,Negative,O,No,Deceased Donor,M,TX,Negative,No,No,No,29.0,0.70,No,Yes,No,No,Yes,NaN,NaN,"ANCEF, FENTANYL, VERSED,LASIX",Yes,Yes,38.0,171.0,0.8,No,No,Negative,Yes,Unknown,Unknown,No,NO,No,No,No,No,No,No,No,No,Positive,HEAD TRAUMA,No,"Accident, Non-MVA",BLUNT INJURY,Yes,Yes,No,172.7,67.1,22.492476,Unknown,Unknown,Unknown,O,Identical,36,DILATED MYOPATHY: IDIOPATHIC,No,3.1,Local,Yes,No,No,185.4,94.8,27.6,0.0,No,Orthotopic Bicaval,No,No,323.0,No,Echo,55.0,No,Biopsy not done,No,Not Done,Positive,Negative,No,Dopamine,No,2013,Yes,2012,6 - 10,Yes,100.0,28.0,No,Normal,Normal,Abnormal-left,7.50,27.8
2,0,DILATED MYOPATHY: ISCHEMIC,M,O,106.000,175.0,34.5096,US Citizen,NY,ATTENDED COLLEGE/TECHNICAL SCHOOL,Yes,Yes,No,No,No,No,None,Unknown,"10% - Moribund, fatal processes progressing rapidly",Private insurance,DILATED MYOPATHY: ISCHEMIC,No,No dialysis,No,No,1.4,No,52.0,23.0,32.0,NaN,5.00,Yes,Yes,Yes,Unknown,Yes,No,Unknown,Yes,"CABG; Other, specify",HR: Status 1A,Yes,55.0,Hypoplastic Left Heart Syndrome; Atrioventricular Septal Defect; Other left Heart Valvar/Structural,58,Yes,"White, Non-Hispanic",175.3,106.0,34.5,175.3,106.0,34.5,998,Yes,Region 9,No,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,"20% - Very sick, hospitalization necessary: active treatment necessary",Hospitalized Not in ICU,Private insurance,No,NY,No,No,2.19,No,4.40,21.0,22.0,13.0,28.0,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,1.2,Yes,None,Unknown,Yes,No,No,"CABG; Other, specify",Negative,Negative,Unknown,Negative,Negative,Negative,Positive,Unknown,Unknown,Unknown,998,2913.0,Yes,501,No,No,Yes,No,No,2,3,7,44,11,15,2,3,35,44,4,13,0,1,2,3,No,Negative,Negative,US Citizen,No,15,"White, Non-Hispanic",Negative,Negative,O,No,Deceased Donor,M,NY,Negative,No,No,No,15.0,0.74,No,Yes,Yes,No,Yes,"AMPHOTERICIN, BETADINE",ZANTAC,"ZOSYN, VANCOMYCIN",Yes,Yes,445.0,217.0,0.7,No,No,Negative,Yes,Unknown,Yes,No,NO,No,No,No,No,No,No,Yes,No,Negative,ANOXIA,No,NONE OF THE ABOVE,DRUG INTOXICATION,Yes,Yes,No,170.0,59.0,20.415225,Unknown,Unknown,Unknown,O,Identical,58,DILATED MYOPATHY: ISCHEMIC,No,1.4,Local,Yes,Yes,No,175.3,90.7,29.5,0.0,Yes,Orthotopic Bicaval,No,No,401.0,No,Echo,60.0,No,Biopsy not done,No,Not Done,Negative,Negative,No,"Other, specify",No,2013,Yes,2012,NONE,Yes,100.0,41.0,No,Normal,Unknwn,Abnormal-both,7.40,25.4
3,0,DILATED MYOPATHY: ISCHEMIC,M,A,111.000,178.0,35.0335,US Citizen,NY,HIGH SCHOOL (9-12) or GED,No,No,No,Yes,No,No,Lvad+Rvad,CentriMag (Thoratec/Levitronix),"20% - Very sick, hospitalization necessary: active treatment necessary",Public insurance - Medicare & Choice,DILATED MYOPATHY: ISCHEMIC,No,No dialysis,No,No,1.1,No,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown,Unknown,Unknown,Unknown,Yes,0-2 months,Yes,"Other, specify",HR: Status 1A,Yes,392.0,Hypoplastic Left Heart Syndrome; Atrioventricular Septal Defect; Other left Heart Valvar/Structural,65,Yes,"White, Non-Hispanic",178.0,111.0,35.0,178.0,111.6,35.2,2016-06-07 00:00:00,No,Region 9,No,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,80% - Normal activity with effort: some symptoms of disease,Not Hospitalized,Private insurance,No,NY,No,No,1.35,No,4.80,12.0,22.0,12.0,34.0,No,No,No,No,No,No,No,No,No,No,No,0.7,Yes,Lvad,Heartmate II,Yes,No,No,"Other, specify",Negative,Negative,Unknown,Negative,Negative,Negative,Positive,Unknown,Unknown,Unknown,2003,1225.0,Yes,501,No,Yes,Yes,No,No,33,68,39,51,1,8,24,26,35,38,4,11,2,2,2,6,No,Negative,Not Done,US Citizen,No,47,"White, Non-Hispanic",Negative,Negative,A1,No,Deceased Donor,F,NY,Negative,No,Yes,Yes,29.0,1.34,No,Yes,Yes,No,Yes,"D50, DOPAMINE, DIFLUCAN",NaN,"KCL, VANCO, MAG, ZOSYN",Yes,Yes,248.0,165.0,0.3,Yes,No,Negative,Yes,Unknown,Yes,No,"SKIN - SQUAMOUS, BASAL CELL",Yes,Yes,No,Yes,No,No,Yes,No,Positive,CEREBROVASCULAR/STROKE,No,DEATH FROM NATURAL CAUSES,INTRACRANIAL HEMORRHAGE/STROKE,Yes,Yes,Yes,163.0,115.2,43.358802,Unknown,Unknown,Unknown,O,Identical,66,DILATED MYOPATHY: ISCHEMIC,No,3.5,Regional,Yes,Yes,No,177.8,113.0,35.7,252.0,Yes,Orthotopic Bicaval,Yes,No,267.0,No,Echo,60.0,"Yes, normal",Biopsy not done,Yes,Not Done,Positive,Negative,No,Unknown,No,2013,No,2012,NONE,Yes,100.0,36.0,No,Unknwn,Unknwn,Abnormal-both,7.37,38.3
4,0,DILATED MYOPATHY: IDIOPATHIC,M,A,72.000,172.0,24.3375,US Citizen,NC,ASSOCIATE/BACHELOR DEGREE,No,No,No,No,No,No,Lvad,Heartmate II,90% - Able to carry on normal activity: minor symptoms of disease,Public insurance - Medicare & Choice,VALVULAR HEART DISEASE,No,No dialysis,No,No,0.8,Yes,30.0,15.0,20.0,15.0,4.75,No,No,No,No,No,No,Unknown,Yes,"Other, specify",HR: Status 1B,Yes,42.0,Hypoplastic Left Heart Syndrome; Atrioventricular Septal Defect; Other left Heart Valvar/Structural,70,Yes,"White, Non-Hispanic",172.0,72.0,24.3,172.0,72.0,24.3,998,No,Region 11,No,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,90% - Able to carry on normal activity: minor symptoms of disease,Not Hospitalized,Public insurance - Medicare & Choice,No,NC,No,No,0.80,No,4.75,15.0,20.0,15.0,30.0,No,No,No,No,No,No,No,No,No,No,No,0.8,No,Lvad,Heartmate II,No,No,No,Unknown,Negative,Negative,Unknown,Positive,Negative,Negative,Positive,Unknown,Unknown,Unknown,998,2785.0,Yes,501,No,Yes,Yes,No,No,3,24,61,64,7,15,3,24,7,38,13,14,0,2,2,4,No,Positive,Negative,US Citizen,No,22,"White, Non-Hispanic",Negative,Negative,A2,No,Deceased Donor,F,NC,Negative,No,Yes,No,70.0,5.10,No,Yes,Yes,No,Yes,"ZOSYN, CIPROFLOXACIN","BUMETIDE, ANCEF","ROCURONIUM, VECURONIUM",Yes,Yes,137.0,174.0,0.5,No,No,Negative,Yes,Unknown,Yes,No,NO,No,No,No,No,No,No,Yes,No,Positive,ANOXIA,No,SUICIDE,DRUG INTOXICATION,Yes,No,Yes,182.9,113.0,33.786719,Unknown,Unknown,Unknown,O,Identical,70,DILATED MYOPATHY: IDIOPATHIC,No,2.8,Local,Yes,No,No,173.0,72.0,24.1,60.0,No,Orthotopic Bicaval,No,Yes,209.0,No,Echo,55.0,No,Biopsy not done,Yes,Positive,Positive,Negative,No,Unknown,No,2013,No,2012,NONE,Yes,100.0,33.0,No,Normal,Unknwn,Abnormal-both,7.51,30.7

In [12]:
df.info(max_cols=df.shape[1])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30725 entries, 0 to 30724
Data columns (total 245 columns):
 #    Column                                        Non-Null Count  Dtype
---   ------                                        --------------  -----
 0    PreviousTransplantNumber_CAN                  30725 non-null  category
 1    WaitListDiagnosisCode_CAN                     30725 non-null  category
 2    Gender_CAN                                    30725 non-null  category
 3    BloodGroup_CAN                                30725 non-null  category
 4    Weight_kg_Registrsation_CAN                   30673 non-null  float64
 5    Height_cm_Registration_CAN                    30608 non-null  float64
 6    BMI_Listing_CAN                               30606 non-null  float64
 7    Citizenship_CAN                               30725 non-null  category
 8    ResidencyStateRegistration_CAN                30725 non-null  category
 9    EducationLevel_CAN                            30725 non-null  category
 10   LifeSupportRegistration_ECMO_CAN              30725 non-null  category
 11   LifeSupportRegistration_IABP_CAN              30725 non-null  category
 12   LifeSupportInhaled_CAN                        30725 non-null  category
 13   InotropesIVRegistration_CAN                   30725 non-null  category
 14   LifeSupportRegistration_PGE_CAN               30725 non-null  category
 15   LifeSupportMechanismRegistration_OTHER_CAN    30725 non-null  category
 16   VentricularDeviceTypeRegistration_CAN         30725 non-null  category
 17   VentricularDeviceBrandRegistration_CAN        30725 non-null  category
 18   FunctionalStatusRegistration_CAN              30725 non-null  category
 19   PrimaryPaymentRegistration_CAN                30725 non-null  category
 20   DiagnosisAtListing_CAN                        30725 non-null  category
 21   DiabetesType_CAN                              30725 non-null  category
 22   DialysisTypeRegistration_CAN                  30725 non-null  category
 23   CerebroVascularDisease_CAN                    30725 non-null  category
 24   PreviousMalignancy_CAN                        30725 non-null  category
 25   CreatinineRegistration_CAN                    30569 non-null  float64
 26   DefibrillatorImplantRegistration_CAN          30725 non-null  category
 27   HemodynamicsRegistration_SYS_CAN              29613 non-null  float64
 28   HemodynamicsRegistration_PA_DIA_CAN           29591 non-null  float64
 29   HemodynamicsRegistration_PA_MN_CAN            29274 non-null  float64
 30   HemodynamicsRegistration_PCW_CAN              27801 non-null  float64
 31   HemodynamicsRegistration_CO_CAN               28924 non-null  float64
 32   InotropesVasodilatorsRegistration_SYS_CAN     30725 non-null  category
 33   InotropesVasodilatorsRegistration_DIA_CAN     30725 non-null  category
 34   InotropesVasodilatorsRegistration_MN_CAN      30725 non-null  category
 35   InotropesVasodilatorsRegistration_PCW_CAN     30725 non-null  category
 36   InotropesVasodilatorsRegistration_CO_CAN      30725 non-null  category
 37   CigaretteUse_CAN                              30725 non-null  category
 38   CigaretteAbstinence_CAN                       30725 non-null  category
 39   PriorCardiacSurgery_CAN                       30725 non-null  category
 40   PriorCardiacSurgeryType_CAN                   30725 non-null  category
 41   InitialWaitingListStatusCode_CAN              30725 non-null  category
 42   ReceivedDeceasedDonorTramsplant_CAN           30725 non-null  object
 43   TotalDayWaitList_CAN                          30725 non-null  float64
 44   StatusAtTransplant_CAN                        30725 non-null  category
 45   Age_Listing_CAN                               30725 non-null  int64
 46   LifeSupportRegistration_CAN                   30725 non-null  category
 47   Ethnicity_CAN                                 30725 non-null  category
 48   Height_cm_Listing_CAN                         30724 non-null  float64
 49   Weight_kg_Listing_CAN                         30703 non-null  float64
 50   BMI_Listing_CALC_CAN                          30682 non-null  float64
 51   Height_cm_Removal_CAN                         30725 non-null  float64
 52   Weight_kg_Removal_CAN                         30718 non-null  float64
 53   BMI_Removal_CAN                               30712 non-null  float64
 54   COMPOSITE_DEATH_DATE                          30725 non-null  object
 55   VentilatorRegistration_CAN                    30725 non-null  category
 56   TransplantRegion_CAN                          30725 non-null  category
 57   WorkIncomeRegistration_CAN                    30725 non-null  category
 58   AntigenBW4_CAN                                30725 non-null  category
 59   AntigenBW6_CAN                                30725 non-null  category
 60   AntigenC1_CAN                                 30725 non-null  category
 61   AntigenC2_CAN                                 30725 non-null  category
 62   AntigenDR51_CAN                               30725 non-null  category
 63   AntigenDR51_2_CAN                             30725 non-null  category
 64   AntigenDR52_CAN                               30725 non-null  category
 65   AntigenDR52_2_CAN                             30725 non-null  category
 66   AntigenDR53_CAN                               30725 non-null  category
 67   AntigenDR53_2_CAN                             30725 non-null  category
 68   AntigenDQ1_CAN                                30725 non-null  category
 69   AntigenDQ2_CAN                                30725 non-null  category
 70   FunctionalStatusTransplant_CAN                30725 non-null  category
 71   MedicalConditionTransplant_CAN                30725 non-null  category
 72   PrimaryPaymentTransplant_CAN                  30725 non-null  category
 73   LifeSupportTransplant_ECMO_CAN                30725 non-null  category
 74   ResidencyStateTransplant_CAN                  30725 non-null  category
 75   WorkIncomeTransplant_CAN                      30725 non-null  category
 76   LifeSupportTransplant_PGE_CAN                 30725 non-null  category
 77   CreatinineTransplant_CAN                      30304 non-null  float64
 78   DialysisBetweenRegistrationTransplant_CAN     30725 non-null  category
 79   HemodynamicsTransplant_CO_CAN                 28985 non-null  float64
 80   HemodynamicsTransplant_PA_DIA_CAN             29473 non-null  float64
 81   HemodynamicsTransplant_PA_MN_CAN              29174 non-null  float64
 82   HemodynamicsTransplant_PCW_CAN                28124 non-null  float64
 83   HemodynamicsTransplant_SYS_CAN                29497 non-null  float64
 84   LifeSupportTransplant_IABP_CAN                30725 non-null  category
 85   InfectionTherapyIV_CAN                        30725 non-null  category
 86   InotropesIVTransplant_CAN                     30725 non-null  category
 87   InotropesVasodilatorsTransplant_CO_CAN        30725 non-null  category
 88   InotropesVasodilatorsTransplant_DIA_CAN       30725 non-null  category
 89   InotropesVasodilatorsTransplant_MN_CAN        30725 non-null  category
 90   InotropesVasodilatorsTransplant_PCW_CAN       30725 non-null  category
 91   InotropesVasodilatorsTransplant_SYS_CAN       30725 non-null  category
 92   LifeSupportMechanismTransplant_OTHER_CAN      30725 non-null  category
 93   PriorLungSurgeryAfterRegistration_CAN         30725 non-null  category
 94   SteroidsUse_CAN                               30725 non-null  category
 95   TotalBilirubinTransplant_CAN                  30241 non-null  float64
 96   TransfusionAfterRegistration_CAN              30725 non-null  category
 97   VentricularDeviceTypeTransplant_CAN           30725 non-null  category
 98   VentricularDeviceBrandTransplant_CAN          30725 non-null  category
 99   VentilatorySupport_CAN                        30725 non-null  category
 100  VentilatorTransplant_CAN                      30725 non-null  category
 101  LifeSupportInhaledTransplant_CAN              30725 non-null  category
 102  PriorCardiacSurgeryTypeListAndTransplant_CAN  30725 non-null  category
 103  Hepatitis_B_CoreAntibody_CAN                  30725 non-null  category
 104  SurfaceAntigenHEP_B_CAN                       30725 non-null  category
 105  SurfaceHBVAntibodyTotalTransplant_CAN         30725 non-null  category
 106  CMVStatus_Transplant_CAN                      30725 non-null  category
 107  HIV_SeroStatusTransplant_CAN                  30725 non-null  category
 108  HEP_C_SerostatusStatus_CAN                    30725 non-null  category
 109  EpsteinBarrSeroStatusTransplant_CAN           30725 non-null  category
 110  HIV_NAT_PreTransplant_CAN                     30725 non-null  category
 111  HCV_NAT_PreTranspant_CAN                      30725 non-null  category
 112  HBV_NAT_Result_CAN                            30725 non-null  category
 113  COD                                           30725 non-null  object
 114  TransplantSurvivalDay                         30300 non-null  float64
 115  TXHRT                                         30725 non-null  category
 116  TransplantProcedure_CAN                       30725 non-null  category
 117  LifeSupportInhaledRegistration_CAN            30725 non-null  category
 118  DeceasedRetyped_DON                           30725 non-null  category
 119  CrossMatchDone                                30725 non-null  category
 120  PreviousTransplantSameOrgan_CAN               30725 non-null  category
 121  PreviousTransplantAnyOrgan_CAN                30725 non-null  category
 122  AntigenDA1_DON                                30725 non-null  category
 123  AntigenDA2_DON                                30725 non-null  category
 124  AntigenDB1_DON                                30725 non-null  category
 125  AntigenDB2_DON                                30725 non-null  category
 126  AntigenDDR1_DON                               30725 non-null  category
 127  AntigenDDR2_DON                               30725 non-null  category
 128  AntigenRA1_CAN                                30725 non-null  category
 129  AntigenRA2_CAN                                30725 non-null  category
 130  AntigenRB1_CAN                                30725 non-null  category
 131  AntigenRB2_CAN                                30725 non-null  category
 132  AntigenRDR1_CAN                               30725 non-null  category
 133  AntigenRDR2_CAN                               30725 non-null  category
 134  MismatchLevel_AMIS                            30725 non-null  category
 135  MismatchLevel_BMIS                            30725 non-null  category
 136  MismatchLevel_DRMIS                           30725 non-null  category
 137  MismatchLevel_HLAMIS                          30725 non-null  category
 138  MalignancyBetweenRegistrationTransplant_CAN   30725 non-null  category
 139  CMV_IGG_Transplant_CAN                        30725 non-null  category
 140  CMV_IGM_Transplant_CAN                        30725 non-null  category
 141  Citizenship_DON                               30725 non-null  category
 142  PastCocaineUse_DON                            30725 non-null  category
 143  Age_DON                                       30725 non-null  int64
 144  Ethnicity_DON                                 30725 non-null  category
 145  Hepatitis_B_CoreAntibody_DON                  30725 non-null  category
 146  SurfaceAntigenHEP_B_DON                       30725 non-null  category
 147  BloodGroup_DON                                30725 non-null  category
 148  HeavyAlcoholUse_DON                           30725 non-null  category
 149  DeceasedOrLiving_DON                          30725 non-null  category
 150  Gender_DON                                    30725 non-null  category
 151  ResidencyState_DON                            30725 non-null  category
 152  Antibody_HEP_C_DON                            30725 non-null  category
 153  NonHeartBeating_DON                           30725 non-null  category
 154  AntiHypertensive_DON                          30725 non-null  category
 155  BloodInfectionSource_DON                      30725 non-null  category
 156  BloodUreaNitrogenLevel_DON                    30518 non-null  float64
 157  Creatinine_DON                                30518 non-null  float64
 158  OtherInfectionSource_DON                      30725 non-null  category
 159  Diuretics_DON                                 30725 non-null  category
 160  SteroidsUse_DON                               30725 non-null  category
 161  TriiodothyronineT3_DON                        30725 non-null  category
 162  ThyroxineT4_DON                               30725 non-null  category
 163  OtherMedsText2_DON                            26425 non-null  object
 164  OtherMedsText3_DON                            17962 non-null  object
 165  OtherMedsText1_DON                            29814 non-null  object
 166  PulmonaryInfection_DON                        30725 non-null  category
 167  PULM_INF_CONF_DON                             30725 non-null  category
 168  Level_SGOT_AST_DON                            30514 non-null  float64
 169  Level_SGOT_ALT_DON                            30514 non-null  float64
 170  TerminalTotalBilirubin_DON                    30515 non-null  float64
 171  UrineInfection_DON                            30725 non-null  category
 172  Vasodilators_DON                              30725 non-null  category
 173  AntibodyResultRPR_VDRL_DON                    30725 non-null  category
 174  InfectionClinical_DON                         30725 non-null  category
 175  CocaineUse_DON                                30725 non-null  category
 176  OtherDrugUse_DON                              30725 non-null  category
 177  CancerExtraCranial_DON                        30725 non-null  category
 178  CancerSite_DON                                30725 non-null  category
 179  CigaretteHistory_DON                          30725 non-null  category
 180  HypertensionHistory_DON                       30725 non-null  category
 181  CancerIntraCranial_DON                        30725 non-null  category
 182  CancerHistory_DON                             30725 non-null  category
 183  DiabetesHistory_DON                           30725 non-null  category
 184  Diabetes_DON                                  30725 non-null  category
 185  PastOtherDrugUse_DON                          30725 non-null  category
 186  CancerSkin_DON                                30725 non-null  category
 187  SerologyAntiCMV_DON                           30725 non-null  category
 188  CauseOfDeath_DON                              30725 non-null  category
 189  SyntheticAntiDiureticHormone_DON              30725 non-null  category
 190  DeathCircumstance_DON                         30725 non-null  category
 191  DeathMechanism_DON                            30725 non-null  category
 192  HeparinManagement_DON                         30725 non-null  category
 193  ArginnieManagement_DON                        30725 non-null  category
 194  InsulinManagement_DON                         30725 non-null  category
 195  Height_cm_DON                                 30725 non-null  float64
 196  Weight_kg_DON                                 30721 non-null  float64
 197  BMI_Donation_DON                              30715 non-null  float64
 198  HBV_NAT_Result_DON                            30725 non-null  category
 199  HCV_NAT_Result_DON                            30725 non-null  category
 200  HIV_NAT_Result_DON                            30725 non-null  category
 201  TransplantType_CAN                            30725 non-null  category
 202  BloodGroupMatchLevel                          30725 non-null  category
 203  Age_CAN                                       30725 non-null  int64
 204  PrimaryDiagnosisType_CAN                      30725 non-null  category
 205  DialysisPriorRegistration_CAN                 30725 non-null  category
 206  IschemicTimeHour_DON                          30133 non-null  float64
 207  AllocationType_DON                            30725 non-null  category
 208  LifeSupportTransplant_CAN                     30725 non-null  category
 209  PriorCardiacSurgeryListAndTransplant_CAN      30725 non-null  category
 210  Malignancy_CAN                                30725 non-null  category
 211  Height_cm_CAN                                 30725 non-null  float64
 212  Weight_kg_CAN                                 30718 non-null  float64
 213  BMI_Calc_CAN                                  30712 non-null  float64
 214  DistanceFromDonorHospitaltoTXCenter_CAN       30725 non-null  float64
 215  VentilatorySupportAfterRegistration_CAN       30725 non-null  category
 216  HeartProcedureType_CAN                        30725 non-null  category
 217  UrineProtein_DON                              30725 non-null  category
 218  CardiacArrest_DON                             30725 non-null  category
 219  LungPO2_DON                                   30463 non-null  float64
 220  MyocardialInfarctionHistory_DON               30725 non-null  category
 221  LV_EjectionFractionMedthod_DON                30725 non-null  category
 222  LV_EjectionFractionPercent_DON                30689 non-null  float64
 223  CoronaryAngiogram_DON                         30725 non-null  category
 224  Biopsy_DON                                    30725 non-null  category
 225  Tatoos_DON                                    30725 non-null  category
 226  AntibodyResultHBSAB_DON                       30725 non-null  category
 227  EpsteinBarr_IGG_DON                           30725 non-null  category
 228  EpsteinBarr_IGM_DON                           30725 non-null  category
 229  HIV_Risk_DON                                  30725 non-null  category
 230  InotropicAgent_DON                            30725 non-null  category
 231  KidneyAllocation_DON                          30725 non-null  category
 232  TransplantYear_CAN                            30725 non-null  category
 233  InotropicMedicationProcurement_DON            30725 non-null  category
 234  ListingYear_CAN                               30725 non-null  int64
 235  TransfusionNumber_DON                         30725 non-null  category
 236  LungPO2_Done_DON                              30725 non-null  category
 237  LungPO2_FIO2_DON                              30384 non-null  float64
 238  OrganRecovery_PCO2_DON                        30488 non-null  float64
 239  PulmonaryCatheter_DON                         30725 non-null  category
 240  BronchoscopyLeft_DON                          30725 non-null  category
 241  BronchoscopyRight_DON                         30725 non-null  category
 242  ChestXray_DON                                 30725 non-null  category
 243  BloodPH_DON                                   30494 non-null  float64
 244  Hematocrit_DON                                30519 non-null  float64
dtypes: category(192), float64(43), int64(4), object(6)
memory usage: 18.1+ MB

In [13]:
cols = df.columns[~df.columns.str.endswith(('_DON','_CAN'))].tolist()
cols

['COMPOSITE_DEATH_DATE',
 'COD',
 'TransplantSurvivalDay',
 'TXHRT',
 'CrossMatchDone',
 'MismatchLevel_AMIS',
 'MismatchLevel_BMIS',
 'MismatchLevel_DRMIS',
 'MismatchLevel_HLAMIS',
 'BloodGroupMatchLevel']

In [14]:
df_dict[df_dict.Feature.isin(cols)]

,Feature,Description,Form,FeatureStartDate,FeatureEndDate,FormSection,DataType,SASAnalysisFormat,Comment,OrginalFeature,FeatureType,Information
2,BloodGroupMatchLevel,DONOR-RECIPIENT ABO MATCH LEVEL,CALCULATED,NaT,NaT,,CHAR(1),ABOMAT,,ABO_MAT,Category,FMTNAME: ABOMAT
10,MismatchLevel_AMIS,A LOCUS MISMATCH LEVEL,CALCULATED,NaT,NaT,,NUM,,,AMIS,Category,
18,MismatchLevel_BMIS,B LOCUS MISMATCH LEVEL,CALCULATED,NaT,NaT,,NUM,,,BMIS,Category,
39,COD,RECIPIENT PRIMARY CAUSE OF DEATH,TRF/TRR,1987-10-01,NaT,PATIENT STATUS,NUM,ALL_COD,,COD,Category,FMTNAME: DON_COD
41,COMPOSITE_DEATH_DATE,Composite Patient Death Date from OPTN or Verified from External Sources,TRR/TRF-CALCULATED,NaT,NaT,,NUM,,,COMPOSITE_DEATH_DATE,Category,
49,CrossMatchDone,CROSSMATCH DONE Y/N,RH,1994-04-01,NaT,TEST INFORMATION,CHAR(1),,,CRSMATCH_DONE,Category,N/Y/X to No/Yes/Missing
90,MismatchLevel_DRMIS,DR Locus MISMATCH LEVEL,CALCULATED,NaT,NaT,,NUM,,,DRMIS,Category,
155,MismatchLevel_HLAMIS,HLA MISMATCH LEVEL,CALCULATED,NaT,NaT,,NUM,,,HLAMIS,Category,
246,TransplantSurvivalDay,Patient Survival Time in days (based on composite death date),CALCULATED,NaT,NaT,,NUM,,,PTIME,Numeric,** LABEL **
286,TXHRT,SIMULTANEOUS HEART,CALCULATED,NaT,NaT,,CHAR(1),,,TXHRT,Category,N/Y/U/X to No/Yes/Unknown/Missing

In [15]:
df[cols].describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
COMPOSITE_DEATH_DATE,30725,3069,998,24367,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COD,30725,72,998,25221,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TransplantSurvivalDay,30300.0,NaN,NaN,NaN,1433.407195,1156.055867,0.0,369.0,1120.0,2207.0,4300.0
TXHRT,30725,1,Yes,30725,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CrossMatchDone,30725,3,Yes,28294,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MismatchLevel_AMIS,30725,4,2,14469,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MismatchLevel_BMIS,30725,4,2,20235,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MismatchLevel_DRMIS,30725,4,2,15395,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MismatchLevel_HLAMIS,30725,8,5,10469,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BloodGroupMatchLevel,30725,3,Identical,26298,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# remove label
cols.remove('TransplantSurvivalDay')
# use for both
cols.remove('CrossMatchDone')
cols.remove('MismatchLevel_AMIS')
cols.remove('MismatchLevel_BMIS')
cols.remove('MismatchLevel_DRMIS')
cols.remove('MismatchLevel_HLAMIS')
cols.remove('BloodGroupMatchLevel')
# display
cols

['COMPOSITE_DEATH_DATE', 'COD', 'TXHRT']

In [17]:
# remove unwanted features
df = df.drop(cols, axis=1).copy()

In [18]:
# sanity check
cols = df.columns[~df.columns.str.endswith(('_DON','_CAN'))].tolist()
cols_add = cols
# remove label
cols_add.remove('TransplantSurvivalDay')
# display
cols_add

['CrossMatchDone',
 'MismatchLevel_AMIS',
 'MismatchLevel_BMIS',
 'MismatchLevel_DRMIS',
 'MismatchLevel_HLAMIS',
 'BloodGroupMatchLevel']

In [19]:
u.any_nans(df)

--- Missing Values Found () (Total Rows: 30,725) ---
                                     Count Percentage
OtherMedsText3_DON                   12763   41.5395%
OtherMedsText2_DON                    4300   13.9951%
HemodynamicsRegistration_PCW_CAN      2924    9.5167%
HemodynamicsTransplant_PCW_CAN        2601    8.4654%
HemodynamicsRegistration_CO_CAN       1801    5.8617%
HemodynamicsTransplant_CO_CAN         1740    5.6631%
HemodynamicsTransplant_PA_MN_CAN      1551    5.0480%
HemodynamicsRegistration_PA_MN_CAN    1451    4.7225%
HemodynamicsTransplant_PA_DIA_CAN     1252    4.0749%
HemodynamicsTransplant_SYS_CAN        1228    3.9967%
HemodynamicsRegistration_PA_DIA_CAN   1134    3.6908%
HemodynamicsRegistration_SYS_CAN      1112    3.6192%
OtherMedsText1_DON                     911    2.9650%
IschemicTimeHour_DON                   592    1.9268%
TotalBilirubinTransplant_CAN           484    1.5753%
TransplantSurvivalDay                  425    1.3832%
CreatinineTransplant_CAN               421    1.3702%
LungPO2_FIO2_DON                       341    1.1098%
LungPO2_DON                            262    0.8527%
OrganRecovery_PCO2_DON                 237    0.7714%
BloodPH_DON                            231    0.7518%
Level_SGOT_AST_DON                     211    0.6867%
Level_SGOT_ALT_DON                     211    0.6867%
TerminalTotalBilirubin_DON             210    0.6835%
BloodUreaNitrogenLevel_DON             207    0.6737%
Creatinine_DON                         207    0.6737%
Hematocrit_DON                         206    0.6705%
CreatinineRegistration_CAN             156    0.5077%
BMI_Listing_CAN                        119    0.3873%
Height_cm_Registration_CAN             117    0.3808%
Weight_kg_Registrsation_CAN             52    0.1692%
BMI_Listing_CALC_CAN                    43    0.1400%
LV_EjectionFractionPercent_DON          36    0.1172%
Weight_kg_Listing_CAN                   22    0.0716%
BMI_Removal_CAN                         13    0.0423%
BMI_Calc_CAN                            13    0.0423%
BMI_Donation_DON                        10    0.0325%
Weight_kg_Removal_CAN                    7    0.0228%
Weight_kg_CAN                            7    0.0228%
Weight_kg_DON                            4    0.0130%
Height_cm_Listing_CAN                    1    0.0033%

In [20]:
# remove any NaNs for the label
df.dropna(subset=['TransplantSurvivalDay'], inplace=True)
# shape
df.shape

(30300, 242)

### Ordinal
* In this research, missing or unknown data often reflects something meaningful—like incomplete records, different workflows, or unmeasured risk factors. In this context, we will be treating it as a nominal category. That way, we preserve its interpretability, and our model can account for it as a distinct group, rather than risking an incorrect ordering assumption.

In [21]:
# ordinal features
ordinal_cols = ['PreviousTransplantNumber_CAN', 'EducationLevel_CAN', 'FunctionalStatusRegistration_CAN', 
                'FunctionalStatusTransplant_CAN', 'CigaretteAbstinence_CAN', 'MedicalConditionTransplant_CAN']

# display
df.loc[:, ordinal_cols].head()

,PreviousTransplantNumber_CAN,EducationLevel_CAN,FunctionalStatusRegistration_CAN,FunctionalStatusTransplant_CAN,CigaretteAbstinence_CAN,MedicalConditionTransplant_CAN
0,0,ATTENDED COLLEGE/TECHNICAL SCHOOL,"10% - Moribund, fatal processes progressing rapidly","10% - Moribund, fatal processes progressing rapidly",Unknown,In Intensive Care Unit
1,0,HIGH SCHOOL (9-12) or GED,"10% - Moribund, fatal processes progressing rapidly",90% - Able to carry on normal activity: minor symptoms of disease,Unknown,Not Hospitalized
2,0,ATTENDED COLLEGE/TECHNICAL SCHOOL,"10% - Moribund, fatal processes progressing rapidly","20% - Very sick, hospitalization necessary: active treatment necessary",Unknown,Hospitalized Not in ICU
3,0,HIGH SCHOOL (9-12) or GED,"20% - Very sick, hospitalization necessary: active treatment necessary",80% - Normal activity with effort: some symptoms of disease,0-2 months,Not Hospitalized
4,0,ASSOCIATE/BACHELOR DEGREE,90% - Able to carry on normal activity: minor symptoms of disease,90% - Able to carry on normal activity: minor symptoms of disease,Unknown,Not Hospitalized

#### PreviousTransplantNumber_CAN

In [22]:
# info
feature = u.get_feature_info(df, 'PreviousTransplantNumber_CAN', cat=True)

                              count unique top   freq
PreviousTransplantNumber_CAN  30300      4   0  29303

:::: NaN Count:
PreviousTransplantNumber_CAN    0

--- PreviousTransplantNumber_CAN ---
dtype: category
Categories: ['0', '1', '2', '3']
Ordered: False

#### EducationLevel_CAN

In [23]:
# info
feature = u.get_feature_info(df, 'EducationLevel_CAN', cat=True)

                    count unique                        top   freq
EducationLevel_CAN  30300      7  HIGH SCHOOL (9-12) or GED  11154

:::: NaN Count:
EducationLevel_CAN    0

--- EducationLevel_CAN ---
dtype: category
Categories: ['ASSOCIATE/BACHELOR DEGREE', 'ATTENDED COLLEGE/TECHNICAL SCHOOL', 'GRADE SCHOOL (0-8)', 'HIGH SCHOOL (9-12) or GED', 'NONE', 'POST-COLLEGE GRADUATE DEGREE', 'Unknown']
Ordered: False

#### FunctionalStatus

In [24]:
# info
feature = u.get_feature_info(df, 'FunctionalStatusRegistration_CAN', cat=True)

                                  count unique                                                                     top  freq
FunctionalStatusRegistration_CAN  30300     24  20% - Very sick, hospitalization necessary: active treatment necessary  6797

:::: NaN Count:
FunctionalStatusRegistration_CAN    0

--- FunctionalStatusRegistration_CAN ---
dtype: category
Categories: [996, '10% - Moribund, fatal processes progressing rapidly', '10% - No play; does not get out of bed', '100% - Fully active, normal', '100% - Normal, no complaints, no evidence of disease', '20% - Often sleeping; play entirely limited to very passive activities', '20% - Very sick, hospitalization necessary: active treatment necessary', '30% - In bed; needs assistance even for quiet play', '30% - Severely disabled: hospitalization is indicated, death not imminent', '40% - Disabled: requires special care and assistance', '40% - Mostly in bed; participates in quiet activities', '50% - Can dress but lies around much of day; no active play; can take part in quiet play/activities', '50% - Requires considerable assistance and frequent medical care', '60% - Requires occasional assistance but is able to care for needs', '60% - Up and around, but minimal active play; keeps busy with quieter activities', '70% - Both greater restriction of and less time spent in play activity', '70% - Cares for self: unable to carry on normal activity or active work', '80% - Active, but tires more quickly', '80% - Normal activity with effort: some symptoms of disease', '90% - Able to carry on normal activity: minor symptoms of disease', '90% - Minor restrictions in physically strenuous activity', 'Performs activities of daily living with NO assistance', 'Performs activities of daily living with SOME assistance', 'Unknown']
Ordered: False

In [25]:
df.FunctionalStatusRegistration_CAN.value_counts(dropna=False)

FunctionalStatusRegistration_CAN
20% - Very sick, hospitalization necessary: active treatment necessary                                 6797
70% - Cares for self: unable to carry on normal activity or active work                                4334
40% - Disabled: requires special care and assistance                                                   4122
60% - Requires occasional assistance but is able to care for needs                                     3756
50% - Requires considerable assistance and frequent medical care                                       3229
80% - Normal activity with effort: some symptoms of disease                                            2678
30% - Severely disabled: hospitalization is indicated, death not imminent                              2647
Unknown                                                                                                 973
90% - Able to carry on normal activity: minor symptoms of disease                                       809
10% - Moribund, fatal processes progressing rapidly                                                     677
100% - Normal, no complaints, no evidence of disease                                                    131
80% - Active, but tires more quickly                                                                     34
70% - Both greater restriction of and less time spent in play activity                                   28
60% - Up and around, but minimal active play; keeps busy with quieter activities                         23
90% - Minor restrictions in physically strenuous activity                                                11
50% - Can dress but lies around much of day; no active play; can take part in quiet play/activities      10
Performs activities of daily living with SOME assistance                                                 10
Performs activities of daily living with NO assistance                                                    8
40% - Mostly in bed; participates in quiet activities                                                     6
100% - Fully active, normal                                                                               5
20% - Often sleeping; play entirely limited to very passive activities                                    4
10% - No play; does not get out of bed                                                                    4
30% - In bed; needs assistance even for quiet play                                                        2
996                                                                                                       2
Name: count, dtype: int64

In [26]:
mask = (
    ~df['FunctionalStatusRegistration_CAN'].astype(str).str.contains("%", na=False)
    & (df['FunctionalStatusRegistration_CAN'] != "Unknown")
)

# display
df.loc[mask, ['FunctionalStatusRegistration_CAN', 'FunctionalStatusTransplant_CAN']]

,FunctionalStatusRegistration_CAN,FunctionalStatusTransplant_CAN
3995,Performs activities of daily living with SOME assistance,80% - Normal activity with effort: some symptoms of disease
14942,Performs activities of daily living with SOME assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
24833,Performs activities of daily living with SOME assistance,60% - Requires occasional assistance but is able to care for needs
24866,996,Unknown
25170,Performs activities of daily living with NO assistance,70% - Cares for self: unable to carry on normal activity or active work
25219,Performs activities of daily living with NO assistance,40% - Disabled: requires special care and assistance
25365,Performs activities of daily living with NO assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
25947,996,"20% - Very sick, hospitalization necessary: active treatment necessary"
26069,Performs activities of daily living with NO assistance,80% - Normal activity with effort: some symptoms of disease
26134,Performs activities of daily living with SOME assistance,50% - Requires considerable assistance and frequent medical care
26168,Performs activities of daily living with NO assistance,60% - Requires occasional assistance but is able to care for needs
26179,Performs activities of daily living with SOME assistance,60% - Requires occasional assistance but is able to care for needs
26334,Performs activities of daily living with SOME assistance,60% - Requires occasional assistance but is able to care for needs
26443,Performs activities of daily living with SOME assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
27137,Performs activities of daily living with SOME assistance,40% - Disabled: requires special care and assistance
27775,Performs activities of daily living with SOME assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
28696,Performs activities of daily living with SOME assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
29324,Performs activities of daily living with NO assistance,60% - Requires occasional assistance but is able to care for needs
29435,Performs activities of daily living with NO assistance,70% - Cares for self: unable to carry on normal activity or active work
30318,Performs activities of daily living with NO assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"

In [27]:
# remove these rows (Not Applicable (patient < 1 year old))
df[df["FunctionalStatusRegistration_CAN"].eq(996)]

,PreviousTransplantNumber_CAN,WaitListDiagnosisCode_CAN,Gender_CAN,BloodGroup_CAN,Weight_kg_Registrsation_CAN,Height_cm_Registration_CAN,BMI_Listing_CAN,Citizenship_CAN,ResidencyStateRegistration_CAN,EducationLevel_CAN,LifeSupportRegistration_ECMO_CAN,LifeSupportRegistration_IABP_CAN,LifeSupportInhaled_CAN,InotropesIVRegistration_CAN,LifeSupportRegistration_PGE_CAN,LifeSupportMechanismRegistration_OTHER_CAN,VentricularDeviceTypeRegistration_CAN,VentricularDeviceBrandRegistration_CAN,FunctionalStatusRegistration_CAN,PrimaryPaymentRegistration_CAN,DiagnosisAtListing_CAN,DiabetesType_CAN,DialysisTypeRegistration_CAN,CerebroVascularDisease_CAN,PreviousMalignancy_CAN,CreatinineRegistration_CAN,DefibrillatorImplantRegistration_CAN,HemodynamicsRegistration_SYS_CAN,HemodynamicsRegistration_PA_DIA_CAN,HemodynamicsRegistration_PA_MN_CAN,HemodynamicsRegistration_PCW_CAN,HemodynamicsRegistration_CO_CAN,InotropesVasodilatorsRegistration_SYS_CAN,InotropesVasodilatorsRegistration_DIA_CAN,InotropesVasodilatorsRegistration_MN_CAN,InotropesVasodilatorsRegistration_PCW_CAN,InotropesVasodilatorsRegistration_CO_CAN,CigaretteUse_CAN,CigaretteAbstinence_CAN,PriorCardiacSurgery_CAN,PriorCardiacSurgeryType_CAN,InitialWaitingListStatusCode_CAN,ReceivedDeceasedDonorTramsplant_CAN,TotalDayWaitList_CAN,StatusAtTransplant_CAN,Age_Listing_CAN,LifeSupportRegistration_CAN,Ethnicity_CAN,Height_cm_Listing_CAN,Weight_kg_Listing_CAN,BMI_Listing_CALC_CAN,Height_cm_Removal_CAN,Weight_kg_Removal_CAN,BMI_Removal_CAN,VentilatorRegistration_CAN,TransplantRegion_CAN,WorkIncomeRegistration_CAN,AntigenBW4_CAN,AntigenBW6_CAN,AntigenC1_CAN,AntigenC2_CAN,AntigenDR51_CAN,AntigenDR51_2_CAN,AntigenDR52_CAN,AntigenDR52_2_CAN,AntigenDR53_CAN,AntigenDR53_2_CAN,AntigenDQ1_CAN,AntigenDQ2_CAN,FunctionalStatusTransplant_CAN,MedicalConditionTransplant_CAN,PrimaryPaymentTransplant_CAN,LifeSupportTransplant_ECMO_CAN,ResidencyStateTransplant_CAN,WorkIncomeTransplant_CAN,LifeSupportTransplant_PGE_CAN,CreatinineTransplant_CAN,DialysisBetweenRegistrationTransplant_CAN,HemodynamicsTransplant_CO_CAN,HemodynamicsTransplant_PA_DIA_CAN,HemodynamicsTransplant_PA_MN_CAN,HemodynamicsTransplant_PCW_CAN,HemodynamicsTransplant_SYS_CAN,LifeSupportTransplant_IABP_CAN,InfectionTherapyIV_CAN,InotropesIVTransplant_CAN,InotropesVasodilatorsTransplant_CO_CAN,InotropesVasodilatorsTransplant_DIA_CAN,InotropesVasodilatorsTransplant_MN_CAN,InotropesVasodilatorsTransplant_PCW_CAN,InotropesVasodilatorsTransplant_SYS_CAN,LifeSupportMechanismTransplant_OTHER_CAN,PriorLungSurgeryAfterRegistration_CAN,SteroidsUse_CAN,TotalBilirubinTransplant_CAN,TransfusionAfterRegistration_CAN,VentricularDeviceTypeTransplant_CAN,VentricularDeviceBrandTransplant_CAN,VentilatorySupport_CAN,VentilatorTransplant_CAN,LifeSupportInhaledTransplant_CAN,PriorCardiacSurgeryTypeListAndTransplant_CAN,Hepatitis_B_CoreAntibody_CAN,SurfaceAntigenHEP_B_CAN,SurfaceHBVAntibodyTotalTransplant_CAN,CMVStatus_Transplant_CAN,HIV_SeroStatusTransplant_CAN,HEP_C_SerostatusStatus_CAN,EpsteinBarrSeroStatusTransplant_CAN,HIV_NAT_PreTransplant_CAN,HCV_NAT_PreTranspant_CAN,HBV_NAT_Result_CAN,TransplantSurvivalDay,TransplantProcedure_CAN,LifeSupportInhaledRegistration_CAN,DeceasedRetyped_DON,CrossMatchDone,PreviousTransplantSameOrgan_CAN,PreviousTransplantAnyOrgan_CAN,AntigenDA1_DON,AntigenDA2_DON,AntigenDB1_DON,AntigenDB2_DON,AntigenDDR1_DON,AntigenDDR2_DON,AntigenRA1_CAN,AntigenRA2_CAN,AntigenRB1_CAN,AntigenRB2_CAN,AntigenRDR1_CAN,AntigenRDR2_CAN,MismatchLevel_AMIS,MismatchLevel_BMIS,MismatchLevel_DRMIS,MismatchLevel_HLAMIS,MalignancyBetweenRegistrationTransplant_CAN,CMV_IGG_Transplant_CAN,CMV_IGM_Transplant_CAN,Citizenship_DON,PastCocaineUse_DON,Age_DON,Ethnicity_DON,Hepatitis_B_CoreAntibody_DON,SurfaceAntigenHEP_B_DON,BloodGroup_DON,HeavyAlcoholUse_DON,DeceasedOrLiving_DON,Gender_DON,ResidencyState_DON,Antibody_HEP_C_DON,NonHeartBeating_DON,AntiHypertensive_DON,BloodInfectionSource_DON,BloodUreaNitrogenLevel_DON,Creatinine_DON,OtherInfectionSource_DON,Diuretics_DON,SteroidsUse_DON,TriiodothyronineT3_DON,ThyroxineT4_DON,OtherMedsText2_DON,OtherMedsText3_DON,OtherMedsText1_DON,PulmonaryInfection_DON,PULM_INF_CONF_DON,Level_SGOT_AST_DON,Level_SGOT_ALT_DON,TerminalTotalBilirubin_DON,UrineInfection_DON,Vasodilators_DON,AntibodyResultRPR_VDRL_DON,InfectionClinical_DON,CocaineUse_DON,OtherDrugUse_DON,CancerExtraCranial_DON,CancerSite_DON,CigaretteHistory_DON,HypertensionHistory_DON,CancerIntraCranial_DON,CancerHistory_DON,DiabetesHistory_DON,Diabetes_DON,PastOtherDrugUse_DON,CancerSkin_DON,SerologyAntiCMV_DON,CauseOfDeath_DON,SyntheticAntiDiureticHormone_DON,DeathCircumstance_DON,DeathMechanism_DON,HeparinManagement_DON,ArginnieManagement_DON,InsulinManagement_DON,Height_cm_DON,Weight_kg_DON,BMI_Donation_DON,HBV_NAT_Result_DON,HCV_NAT_Result_DON,HIV_NAT_Result_DON,TransplantType_CAN,BloodGroupMatchLevel,Age_CAN,PrimaryDiagnosisType_CAN,DialysisPriorRegistration_CAN,IschemicTimeHour_DON,AllocationType_DON,LifeSupportTransplant_CAN,PriorCardiacSurgeryListAndTransplant_CAN,Malignancy_CAN,Height_cm_CAN,Weight_kg_CAN,BMI_Calc_CAN,DistanceFromDonorHospitaltoTXCenter_CAN,VentilatorySupportAfterRegistration_CAN,HeartProcedureType_CAN,UrineProtein_DON,CardiacArrest_DON,LungPO2_DON,MyocardialInfarctionHistory_DON,LV_EjectionFractionMedthod_DON,LV_EjectionFractionPercent_DON,CoronaryAngiogram_DON,Biopsy_DON,Tatoos_DON,AntibodyResultHBSAB_DON,EpsteinBarr_IGG_DON,EpsteinBarr_IGM_DON,HIV_Risk_DON,InotropicAgent_DON,KidneyAllocation_DON,TransplantYear_CAN,InotropicMedicationProcurement_DON,ListingYear_CAN,TransfusionNumber_DON,LungPO2_Done_DON,LungPO2_FIO2_DON,OrganRecovery_PCO2_DON,PulmonaryCatheter_DON,BronchoscopyLeft_DON,BronchoscopyRight_DON,ChestXray_DON,BloodPH_DON,Hematocrit_DON
24866,0,RESTRICTIVE MYOPATHY: IDIOPATHIC,M,A,12.0,97.0,12.7537,US Citizen,PA,NONE,No,No,No,Yes,No,No,Unknown,Unknown,996,Private insurance,RESTRICTIVE MYOPATHY: IDIOPATHIC,No,No dialysis,No,No,NaN,No,32.0,18.0,25.0,10.0,1.6,No,No,No,No,No,No,Unknown,Unknown,Unknown,2090,Yes,5081.0,Hypoplastic Left Heart Syndrome; Atrioventricular Septal Defect; Other left Heart Valvar/Structural,6,Yes,"White, Non-Hispanic",97.0,12.0,12.8,138.0,29.2,15.3,No,Region 2,Unknown,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,Unknown,Hospitalized Not in ICU,Public insurance - Medicaid,No,PA,No,No,0.6,No,NaN,NaN,NaN,NaN,NaN,No,Unknown,No,Unknown,Unknown,Unknown,Unknown,Unknown,No,No,Unknown,0.8,Unknown,None,Unknown,No,No,No,Unknown,Negative,Negative,Unknown,Positive,Negative,Not Done,Negative,Unknown,Unknown,Unknown,4022.0,501,No,Yes,Yes,No,No,2,11,7,62,15,4,2,23,62,64,7,13,1,1,2,4,No,Positive,Negative,US Citizen,No,20,"White, Non-Hispanic",Negative,Negative,A1,No,Deceased Donor,F,VA,Negative,No,Yes,No,14.0,0.5,Yes,Yes,No,No,Yes,NaN,NaN,"LABETALOL, KCL",No,Unknown,28.0,38.0,0.5,No,Yes,Negative,Yes,Unknown,Unknown,No,NO,No,No,No,No,No,No,No,No,Negative,ANOXIA,No,DEATH FROM NATURAL CAUSES,DEATH FROM NATURAL CAUSES,Yes,Yes,No,160.0,54.4,21.250027,Unknown,Unknown,Unknown,O,Identical,20,CONGENITAL HEART DEFECT - WITH SURGERY,No,2.9,Regional,No,No,No,135.0,29.5,16.2,159.0,No,Orthotopic Bicaval,No,No,426.0,No,Echo,65.0,No,Biopsy not done,No,Not Done,Positive,Negative,No,"Other, specify",No,2010,Yes,1996,NONE,Yes,100.0,33.0,Yes,Normal,Normal,Normal,7.45,26.8
25947,0,DILATED MYOPATHY: ISCHEMIC,M,B,77.0,188.0,21.8091,US Citizen,PA,HIGH SCHOOL (9-12) or GED,No,Yes,No,Yes,No,No,None,Unknown,996,Private insurance,DILATED MYOPATHY: ISCHEMIC,Type Unknown,No dialysis,No,No,1.2,No,52.0,24.0,33.0,20.0,5.6,No,No,No,No,No,Unknown,Unknown,Unknown,Unknown,HR: Status 1A,Yes,2706.0,Hypoplastic Left Heart Syndrome; Atrioventricular Septal Defect; Other left Heart Valvar/Structural,42,Yes,"White, Non-Hispanic",187.9,77.0,21.8,180.3,85.0,26.1,Yes,Region 2,Unknown,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,No Antigen,"20% - Very sick, hospitalization necessary: active treatment necessary",Hospitalized Not in ICU,Public insurance - Medicare FFS (Fee for Service),No,PA,No,No,0.9,No,3.9,13.0,17.0,7.0,25.0,No,No,No,Yes,Yes,Yes,Yes,Yes,No,No,No,0.4,Yes,Lvad,Heartmate II,Yes,No,No,"Other, specify",Not Done,Negative,Unknown,Positive,Negative,Negative,Positive,Unknown,Unknown,Unknown,4090.0,501,No,Yes,Yes,No,No,1,32,8,64,17,7,2,11,49,62,4,12,2,2,2,6,No,Positive,Not Done,US Citizen,No,17,"White, Non-Hispanic",Negative,Negative,O,No,Deceased Donor,M,SC,Negative,No,Yes,No,6.0,1.0,No,Yes,Yes,No,No,"CACL,KCL,MAGSULFATE,JEVITY 1.2,DIFLUCAN,","AMPHOTERICIN B,BETADINE,0.9%NS","NEO,ZOSYN,VANC,PEPCID,1/2NS MIVF,NARCAN,COMBIVENT,",Yes,Yes,22.0,14.0,0.7,No,Yes,Negative,Yes,Unknown,Unknown,No,NO,No,No,No,No,No,No,No,No,Negative,HEAD TRAUMA,No,"Accident, Non-MVA",GUNSHOT WOUND,Yes,Yes,Yes,170.0,65.0,22.491349,Unknown,Unknown,Unknown,O,Compatible,50,DILATED MYOPATHY: ISCHEMIC,No,3.8,National,Yes,Yes,No,180.3,85.3,26.2,425.0,Yes,Orthotopic Bicaval,No,No,493.0,No,Echo,65.0,No,Biopsy not done,No,Not Done,Negative,Not Done,No,Neosynephrine,No,2010,Yes,2003,1 - 5,Yes,100.0,50.0,Yes,Normal,Normal,Normal,7.32,32.4

In [28]:
# remove these two rows
df = df[df["FunctionalStatusRegistration_CAN"].ne(996)].reset_index(drop=True).copy()

In [29]:
mask = (
    ~df['FunctionalStatusRegistration_CAN'].astype(str).str.contains("%", na=False)
    & (df['FunctionalStatusRegistration_CAN'] != "Unknown")
)

# display
df.loc[mask, ['WorkIncomeRegistration_CAN', 'FunctionalStatusRegistration_CAN', 'FunctionalStatusTransplant_CAN']]

,WorkIncomeRegistration_CAN,FunctionalStatusRegistration_CAN,FunctionalStatusTransplant_CAN
3995,No,Performs activities of daily living with SOME assistance,80% - Normal activity with effort: some symptoms of disease
14942,No,Performs activities of daily living with SOME assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
24408,Unknown,Performs activities of daily living with SOME assistance,60% - Requires occasional assistance but is able to care for needs
24744,No,Performs activities of daily living with NO assistance,70% - Cares for self: unable to carry on normal activity or active work
24793,Unknown,Performs activities of daily living with NO assistance,40% - Disabled: requires special care and assistance
24939,Unknown,Performs activities of daily living with NO assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
25642,Yes,Performs activities of daily living with NO assistance,80% - Normal activity with effort: some symptoms of disease
25707,Unknown,Performs activities of daily living with SOME assistance,50% - Requires considerable assistance and frequent medical care
25741,Unknown,Performs activities of daily living with NO assistance,60% - Requires occasional assistance but is able to care for needs
25752,Unknown,Performs activities of daily living with SOME assistance,60% - Requires occasional assistance but is able to care for needs
25907,Unknown,Performs activities of daily living with SOME assistance,60% - Requires occasional assistance but is able to care for needs
26016,Unknown,Performs activities of daily living with SOME assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
26710,Unknown,Performs activities of daily living with SOME assistance,40% - Disabled: requires special care and assistance
27348,Unknown,Performs activities of daily living with SOME assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
28269,Unknown,Performs activities of daily living with SOME assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
28897,Yes,Performs activities of daily living with NO assistance,60% - Requires occasional assistance but is able to care for needs
29008,No,Performs activities of daily living with NO assistance,70% - Cares for self: unable to carry on normal activity or active work
29891,No,Performs activities of daily living with NO assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"

In [30]:
# mapping
mapping = {'Performs activities of daily living with SOME assistance': '60% - Performs activities of daily living with SOME assistance',
           'Performs activities of daily living with NO assistance': '70% - Performs activities of daily living with NO assistance'}

# apply mapping
df['FunctionalStatusRegistration_CAN'] = df['FunctionalStatusRegistration_CAN'].map(mapping).fillna(df['FunctionalStatusRegistration_CAN'])

In [31]:
# display
df.loc[mask, ['WorkIncomeRegistration_CAN', 'FunctionalStatusRegistration_CAN', 'FunctionalStatusTransplant_CAN']]

,WorkIncomeRegistration_CAN,FunctionalStatusRegistration_CAN,FunctionalStatusTransplant_CAN
3995,No,60% - Performs activities of daily living with SOME assistance,80% - Normal activity with effort: some symptoms of disease
14942,No,60% - Performs activities of daily living with SOME assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
24408,Unknown,60% - Performs activities of daily living with SOME assistance,60% - Requires occasional assistance but is able to care for needs
24744,No,70% - Performs activities of daily living with NO assistance,70% - Cares for self: unable to carry on normal activity or active work
24793,Unknown,70% - Performs activities of daily living with NO assistance,40% - Disabled: requires special care and assistance
24939,Unknown,70% - Performs activities of daily living with NO assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
25642,Yes,70% - Performs activities of daily living with NO assistance,80% - Normal activity with effort: some symptoms of disease
25707,Unknown,60% - Performs activities of daily living with SOME assistance,50% - Requires considerable assistance and frequent medical care
25741,Unknown,70% - Performs activities of daily living with NO assistance,60% - Requires occasional assistance but is able to care for needs
25752,Unknown,60% - Performs activities of daily living with SOME assistance,60% - Requires occasional assistance but is able to care for needs
25907,Unknown,60% - Performs activities of daily living with SOME assistance,60% - Requires occasional assistance but is able to care for needs
26016,Unknown,60% - Performs activities of daily living with SOME assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
26710,Unknown,60% - Performs activities of daily living with SOME assistance,40% - Disabled: requires special care and assistance
27348,Unknown,60% - Performs activities of daily living with SOME assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
28269,Unknown,60% - Performs activities of daily living with SOME assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"
28897,Yes,70% - Performs activities of daily living with NO assistance,60% - Requires occasional assistance but is able to care for needs
29008,No,70% - Performs activities of daily living with NO assistance,70% - Cares for self: unable to carry on normal activity or active work
29891,No,70% - Performs activities of daily living with NO assistance,"20% - Very sick, hospitalization necessary: active treatment necessary"

In [32]:
# regex: 
# Ignore any leading spaces: \s*
# Capture the number just before %: (\d+(?:\.\d+)?)
# Ignore spaces before the %: \s*
# Look ahead to ensure the next character is %  (but don’t consume it): (?=%)
df["FunctionalStatusRegistration_CAN"] = (
    df["FunctionalStatusRegistration_CAN"]
    .str.extract(r"\s*(\d+(?:\.\d+)?)\s*(?=%)", expand=False)
    .astype('category')
)
df["FunctionalStatusTransplant_CAN"] = (
    df["FunctionalStatusTransplant_CAN"]
    .str.extract(r"\s*(\d+(?:\.\d+)?)\s*(?=%)", expand=False)
    .astype('category')
)
#
features = u.get_feature_info(df, 'FunctionalStatus', cat=True)

                                  count unique top  freq
FunctionalStatusRegistration_CAN  29325     10  20  6801
FunctionalStatusTransplant_CAN    28924     10  20  8611

:::: NaN Count:
FunctionalStatusRegistration_CAN     973
FunctionalStatusTransplant_CAN      1374

--- FunctionalStatusRegistration_CAN ---
dtype: category
Categories: ['10', '100', '20', '30', '40', '50', '60', '70', '80', '90']
Ordered: False

--- FunctionalStatusTransplant_CAN ---
dtype: category
Categories: ['10', '100', '20', '30', '40', '50', '60', '70', '80', '90']
Ordered: False

In [33]:
# verify Missing is Random
u.check_informative_missingness(df, 'FunctionalStatusRegistration_CAN', target='TransplantSurvivalDay', unknown_val=None)

--- Missingness (): FunctionalStatusRegistration_CAN ---
Group Sizes:    (Unknown=973, Known=29,325)
Mean survival:  (Unknown=1,184.8d, Known=1,441.5d)
Difference:     -256.7 days

--- Welch's t-test Analysis ---
ρ-Value: 0.0000
RESULT: Missingness is associated with survival (informative missingness).
Interpretation: Not MCAR. Likely MAR or MNAR.

--- Cohen's Analysis ---
Cohen's d:     -0.2222 (Small)
95% CI:        [-0.2861, -0.1583]
Result: INFORMATIVE MISSINGNESS (statistically significant difference; small effect size)

In [34]:
# verify Missing is Random
u.check_informative_missingness(df, 'FunctionalStatusTransplant_CAN', target='TransplantSurvivalDay', unknown_val=None)

--- Missingness (): FunctionalStatusTransplant_CAN ---
Group Sizes:    (Unknown=1,374, Known=28,924)
Mean survival:  (Unknown=1,129.3d, Known=1,447.7d)
Difference:     -318.4 days

--- Welch's t-test Analysis ---
ρ-Value: 0.0000
RESULT: Missingness is associated with survival (informative missingness).
Interpretation: Not MCAR. Likely MAR or MNAR.

--- Cohen's Analysis ---
Cohen's d:     -0.2759 (Small)
95% CI:        [-0.3300, -0.2217]
Result: INFORMATIVE MISSINGNESS (statistically significant difference; small effect size)

In [35]:
# display
df.loc[:,['WorkIncomeRegistration_CAN', 'FunctionalStatusRegistration_CAN', 'FunctionalStatusTransplant_CAN']].sample(n=5, random_state=SEED)

,WorkIncomeRegistration_CAN,FunctionalStatusRegistration_CAN,FunctionalStatusTransplant_CAN
24713,No,30,20
12770,No,60,50
12524,No,10,20
14592,No,30,60
15126,No,80,NaN

#### CigaretteAbstinence_CAN

In [36]:
# info
feature = u.get_feature_info(df, 'CigaretteAbstinence_CAN', cat=True)

                         count unique      top   freq
CigaretteAbstinence_CAN  30298     10  Unknown  16933

:::: NaN Count:
CigaretteAbstinence_CAN    0

--- CigaretteAbstinence_CAN ---
dtype: category
Categories: ['0-2 months', '13-24 months', '25-36 months', '3-12 months', '37-48 months', '49-60 months', '>60 months', 'Continues to smoke', 'Unknown', 'Unknown duration']
Ordered: False

In [37]:
# verify Missing is Random
u.check_informative_missingness(df, 'CigaretteAbstinence_CAN', target='TransplantSurvivalDay', unknown_val='Unknown')

--- Missingness (): CigaretteAbstinence_CAN ---
Group Sizes:    (Unknown=16,933, Known=13,365)
Mean survival:  (Unknown=1,420.2d, Known=1,449.7d)
Difference:     -29.5 days

--- Welch's t-test Analysis ---
ρ-Value: 0.0270
RESULT: Missingness is associated with survival (informative missingness).
Interpretation: Not MCAR. Likely MAR or MNAR.

--- Cohen's Analysis ---
Cohen's d:     -0.0256 (Negligible)
95% CI:        [-0.0482, -0.0029]
Result: INFORMATIVE MISSINGNESS (statistically significant difference; small effect size)

#### MedicalConditionTransplant_CAN

In [38]:
# info
feature = u.get_feature_info(df, 'MedicalConditionTransplant_CAN', cat=True)

                                count unique               top   freq
MedicalConditionTransplant_CAN  30298      4  Not Hospitalized  14506

:::: NaN Count:
MedicalConditionTransplant_CAN    0

--- MedicalConditionTransplant_CAN ---
dtype: category
Categories: ['Hospitalized Not in ICU', 'In Intensive Care Unit', 'Not Hospitalized', 'Unknown']
Ordered: False

In [39]:
# verify Missing is Random
u.check_informative_missingness(df, feature[0], target='TransplantSurvivalDay', unknown_val='Unknown')

--- Missingness (): MedicalConditionTransplant_CAN ---
Group Sizes:    (Unknown=45, Known=30,253)
Mean survival:  (Unknown=102.4d, Known=1,435.2d)
Difference:     -1,332.8 days

--- Welch's t-test Analysis ---
ρ-Value: 0.0000
RESULT: Missingness is associated with survival (informative missingness).
Interpretation: Not MCAR. Likely MAR or MNAR.

--- Cohen's Analysis ---
Cohen's d:     -1.1542 (Large)
95% CI:        [-1.4467, -0.8616]
Result: INFORMATIVE MISSINGNESS (statistically significant difference; small effect size)

### Binary Columns

In [40]:
# display category features
_ = get_column_summary(df, cat = 2, flag=False, ignore_list=None)

--- Found 22 Columns (Threshold: <= 2) ---
Gender_CAN : ['M', 'F']
LifeSupportRegistration_ECMO_CAN : ['No', 'Yes']
LifeSupportRegistration_IABP_CAN : ['No', 'Yes']
LifeSupportInhaled_CAN : ['No', 'Yes']
InotropesIVRegistration_CAN : ['No', 'Yes']
LifeSupportRegistration_PGE_CAN : ['No', 'Yes']
LifeSupportMechanismRegistration_OTHER_CAN : ['Yes', 'No']
ReceivedDeceasedDonorTramsplant_CAN : ['Yes', 'No']
VentilatorRegistration_CAN : ['No', 'Yes']
LifeSupportTransplant_ECMO_CAN : ['No', 'Yes']
LifeSupportTransplant_PGE_CAN : ['No', 'Yes']
LifeSupportTransplant_IABP_CAN : ['No', 'Yes']
InotropesIVTransplant_CAN : ['No', 'Yes']
LifeSupportMechanismTransplant_OTHER_CAN : ['Yes', 'No']
VentilatorTransplant_CAN : ['No', 'Yes']
LifeSupportInhaledTransplant_CAN : ['No', 'Yes']
TransplantProcedure_CAN : ['501']
LifeSupportInhaledRegistration_CAN : ['No', 'Yes']
PreviousTransplantSameOrgan_CAN : ['No', 'Yes']
PreviousTransplantAnyOrgan_CAN : ['No', 'Yes']
DeceasedOrLiving_DON : ['Deceased Donor', 'Living Donor']
Gender_DON : ['M', 'F']

In [41]:
df.TransplantProcedure_CAN.value_counts()

TransplantProcedure_CAN
501    30298
Name: count, dtype: int64

In [42]:
# add to remove cols list
remove_cols = ['TransplantProcedure_CAN']

In [43]:
# ignore for next run
ignore_cols = get_cols_by_cardinality(df, 2, dropna=True, flag=False)
# display category features
cols = get_column_summary(df, cat = 3, flag=False, ignore_list=ignore_cols)

--- Found 74 Columns (Threshold: <= 3) ---
CerebroVascularDisease_CAN : ['No', 'Yes', 'Unknown']
PreviousMalignancy_CAN : ['No', 'Yes', 'Unknown']
DefibrillatorImplantRegistration_CAN : ['Yes', 'No', 'Unknown']
InotropesVasodilatorsRegistration_SYS_CAN : ['Yes', 'No', 'Unknown']
InotropesVasodilatorsRegistration_DIA_CAN : ['Yes', 'No', 'Unknown']
InotropesVasodilatorsRegistration_MN_CAN : ['Yes', 'No', 'Unknown']
InotropesVasodilatorsRegistration_PCW_CAN : ['Yes', 'No', 'Unknown']
InotropesVasodilatorsRegistration_CO_CAN : ['Yes', 'No', 'Unknown']
CigaretteUse_CAN : ['No', 'Yes', 'Unknown']
PriorCardiacSurgery_CAN : ['Yes', 'No', 'Unknown']
LifeSupportRegistration_CAN : ['Yes', 'No', 'Unknown']
WorkIncomeRegistration_CAN : ['No', 'Yes', 'Unknown']
WorkIncomeTransplant_CAN : ['No', 'Unknown', 'Yes']
DialysisBetweenRegistrationTransplant_CAN : ['No', 'Yes', 'Unknown']
InfectionTherapyIV_CAN : ['No', 'Unknown', 'Yes']
InotropesVasodilatorsTransplant_CO_CAN : ['Unknown', 'No', 'Yes']
InotropesVasodilatorsTransplant_DIA_CAN : ['Unknown', 'No', 'Yes']
InotropesVasodilatorsTransplant_MN_CAN : ['Unknown', 'No', 'Yes']
InotropesVasodilatorsTransplant_PCW_CAN : ['Unknown', 'No', 'Yes']
InotropesVasodilatorsTransplant_SYS_CAN : ['Unknown', 'No', 'Yes']
PriorLungSurgeryAfterRegistration_CAN : ['No', 'Yes', 'Unknown']
SteroidsUse_CAN : ['No', 'Yes', 'Unknown']
TransfusionAfterRegistration_CAN : ['No', 'Yes', 'Unknown']
VentilatorySupport_CAN : ['Yes', 'No', 'Unknown']
DeceasedRetyped_DON : ['No', 'Yes', 'Unknown']
CrossMatchDone : ['No', 'Yes', 'Unknown']
MalignancyBetweenRegistrationTransplant_CAN : ['No', 'Unknown', 'Yes']
PastCocaineUse_DON : ['No', 'Yes', 'Unknown']
HeavyAlcoholUse_DON : ['No', 'Yes', 'Unknown']
NonHeartBeating_DON : ['No', 'Unknown', 'Yes']
AntiHypertensive_DON : ['Yes', 'No', 'Unknown']
BloodInfectionSource_DON : ['No', 'Yes', 'Unknown']
OtherInfectionSource_DON : ['No', 'Unknown', 'Yes']
Diuretics_DON : ['Yes', 'No', 'Unknown']
SteroidsUse_DON : ['No', 'Yes', 'Unknown']
TriiodothyronineT3_DON : ['No', 'Yes', 'Unknown']
ThyroxineT4_DON : ['No', 'Yes', 'Unknown']
PulmonaryInfection_DON : ['Yes', 'No', 'Unknown']
PULM_INF_CONF_DON : ['Yes', 'Unknown', 'No']
UrineInfection_DON : ['No', 'Yes', 'Unknown']
Vasodilators_DON : ['No', 'Yes', 'Unknown']
InfectionClinical_DON : ['Yes', 'No', 'Unknown']
CocaineUse_DON : ['Unknown', 'No', 'Yes']
OtherDrugUse_DON : ['Unknown', 'Yes', 'No']
CancerExtraCranial_DON : ['No', 'Unknown', 'Yes']
CigaretteHistory_DON : ['No', 'Yes', 'Unknown']
HypertensionHistory_DON : ['No', 'Yes', 'Unknown']
CancerIntraCranial_DON : ['No', 'Unknown', 'Yes']
CancerHistory_DON : ['No', 'Yes', 'Unknown']
Diabetes_DON : ['No', 'Yes', 'Unknown']
PastOtherDrugUse_DON : ['No', 'Yes', 'Unknown']
CancerSkin_DON : ['No', 'Yes', 'Unknown']
SyntheticAntiDiureticHormone_DON : ['Yes', 'No', 'Unknown']
HeparinManagement_DON : ['Yes', 'No', 'Unknown']
ArginnieManagement_DON : ['No', 'Yes', 'Unknown']
InsulinManagement_DON : ['Yes', 'No', 'Unknown']
HIV_NAT_Result_DON : ['Unknown', 'Negative', 'Not Done']
TransplantType_CAN : ['O', 'H', 'Unknown']
BloodGroupMatchLevel : ['Identical', 'Compatible', 'Incompatible']
DialysisPriorRegistration_CAN : ['No', 'Yes', 'Unknown']
LifeSupportTransplant_CAN : ['Yes', 'No', 'Unknown']
PriorCardiacSurgeryListAndTransplant_CAN : ['Yes', 'No', 'Unknown']
Malignancy_CAN : ['No', 'Yes', 'Unknown']
VentilatorySupportAfterRegistration_CAN : ['Yes', 'No', 'Unknown']
UrineProtein_DON : ['No', 'Yes', 'Unknown']
CardiacArrest_DON : ['No', 'Yes', 'Unknown']
MyocardialInfarctionHistory_DON : ['No', 'Yes', 'Unknown']
LV_EjectionFractionMedthod_DON : ['Echo', 'Angiogram', 'Unknown']
Tatoos_DON : ['Yes', 'No', 'Unknown']
HIV_Risk_DON : ['No', 'Yes', 'Unknown']
KidneyAllocation_DON : ['No', 'Yes', 'Unknown']
InotropicMedicationProcurement_DON : ['No', 'Yes', 'Unknown']
LungPO2_Done_DON : ['Yes', 'No', 'Unknown']
PulmonaryCatheter_DON : ['No', 'Yes', 'Unknown']

In [44]:
# verify Missing is Random
u.check_informative_missingness(df, 'TransplantType_CAN', target='TransplantSurvivalDay', unknown_val='Unknown')

--- Missingness (): TransplantType_CAN ---
Group Sizes:    (Unknown=54, Known=30,244)
Mean survival:  (Unknown=99.6d, Known=1,435.6d)
Difference:     -1,336.0 days

--- Welch's t-test Analysis ---
ρ-Value: 0.0000
RESULT: Missingness is associated with survival (informative missingness).
Interpretation: Not MCAR. Likely MAR or MNAR.

--- Cohen's Analysis ---
Cohen's d:     -1.1571 (Large)
95% CI:        [-1.4243, -0.8900]
Result: INFORMATIVE MISSINGNESS (statistically significant difference; small effect size)

In [45]:
# no value added
df = df.drop(remove_cols, axis=1).copy()

### Candidate

In [46]:
# keep candidate and TransplantSurvivalDay features
cols = df.columns[df.columns.str.contains("CAN")].to_list()
cols.extend(['TransplantSurvivalDay'])
cols.extend(cols_add)

# all the candidates' features and TransplantSurvivalDay
df_can = df[cols]

# display
df_can.shape

(30298, 146)

### Donor

In [47]:
# keep donor and TransplantSurvivalDay features
cols = df.columns[df.columns.str.contains("DON")].to_list()
cols.extend(['TransplantSurvivalDay'])
cols.extend(cols_add)

# all the candidates' features and TransplantSurvivalDay
df_don = df[cols]

# display
df_don.shape

(30298, 102)

In [48]:
# sanity check
df.shape[1], df_can.shape[1] + df_don.shape[1]

(241, 248)

#### Write to Disk: Full Data

In [49]:
# save data: heart dataset
u.write_to_file(df_don, 'DON_Heart_Data',path='../Data/', format='pkl')
u.write_to_file(df_can, 'CAN_Heart_Data',path='../Data/', format='pkl')

30,298 records written to ../Data/DON_Heart_Data.pkl
30,298 records written to ../Data/CAN_Heart_Data.pkl