In [1]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer  # noqa
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import BayesianRidge


# Example toy data (3 features, some NaNs)
df = pd.DataFrame({
    "HR":  [70, 85, np.nan, 90, 76],
    "MAP": [93, np.nan, 100, 105, 88],
    "CI":  [2.6, 3.0, 3.2, np.nan, 2.8],
})

In [2]:
imputer = IterativeImputer(
    estimator=LinearRegression(),
    max_iter=10,
    initial_strategy="mean",
    random_state=42,
)

In [5]:
imputer = IterativeImputer(
    estimator=LinearRegression(),
    max_iter=10,
    initial_strategy="median",
    random_state=42,
)

In [3]:
imputed_array = imputer.fit_transform(df)
df_imputed = pd.DataFrame(imputed_array, columns=df.columns)

print(df_imputed)

          HR         MAP        CI
0  70.000000   93.000000  2.600000
1  85.000000   92.273752  3.000000
2  95.117929  100.000000  3.200000
3  90.000000  105.000000  3.023156
4  76.000000   88.000000  2.800000

In [6]:
imputed_array = imputer.fit_transform(df)
df_imputed = pd.DataFrame(imputed_array, columns=df.columns)

print(df_imputed)

          HR         MAP        CI
0  70.000000   93.000000  2.600000
1  85.000000   92.273752  3.000000
2  95.117929  100.000000  3.200000
3  90.000000  105.000000  3.023156
4  76.000000   88.000000  2.800000

In [9]:
mice = IterativeImputer(
    estimator=BayesianRidge(),
    initial_strategy="median",
    max_iter=10,
    random_state=0
)

In [10]:
imputed_array = mice.fit_transform(df)
df_imputed = pd.DataFrame(imputed_array, columns=df.columns)

print(df_imputed)

          HR         MAP        CI
0  70.000000   93.000000  2.600000
1  85.000000   99.749267  3.000000
2  83.434862  100.000000  3.200000
3  90.000000  105.000000  3.256799
4  76.000000   88.000000  2.800000

In [12]:
df.corr()

           HR       MAP        CI
HR   1.000000  0.832696  0.993399
MAP  0.832696  1.000000  0.724049
CI   0.993399  0.724049  1.000000

In [13]:
df_imputed.corr()

           HR       MAP        CI
HR   1.000000  0.853639  0.944028
MAP  0.853639  1.000000  0.830199
CI   0.944028  0.830199  1.000000

In [14]:
imputed_array = imputer.fit_transform(df)
df_imputed = pd.DataFrame(imputed_array, columns=df.columns)

print(df_imputed)

          HR         MAP        CI
0  70.000000   93.000000  2.600000
1  85.000000   92.273752  3.000000
2  95.117929  100.000000  3.200000
3  90.000000  105.000000  3.023156
4  76.000000   88.000000  2.800000

In [15]:
df_imputed.corr()

           HR       MAP        CI
HR   1.000000  0.720761  0.984905
MAP  0.720761  1.000000  0.589893
CI   0.984905  0.589893  1.000000

In [28]:
# Set up MICE with Bayesian Ridge
imputer = IterativeImputer(
    estimator=BayesianLasso(),
    max_iter=10,
    n_nearest_features=10,  # only use 10 most correlated vars per target
    random_state=0
)

NameError: name 'BayesianLasso' is not defined

In [16]:
# Set up MICE with Bayesian Ridge
imputer = IterativeImputer(
    estimator=BayesianRidge(),
    max_iter=10,
    n_nearest_features=10,  # only use 10 most correlated vars per target
    random_state=0
)

In [17]:
imputed_array = imputer.fit_transform(df)
df_imputed = pd.DataFrame(imputed_array, columns=df.columns)

print(df_imputed)

          HR         MAP        CI
0  70.000000   93.000000  2.600000
1  85.000000   99.749267  3.000000
2  83.434862  100.000000  3.200000
3  90.000000  105.000000  3.256799
4  76.000000   88.000000  2.800000

In [20]:
df_imputed.corr()

           HR       MAP        CI
HR   1.000000  0.853639  0.944028
MAP  0.853639  1.000000  0.830199
CI   0.944028  0.830199  1.000000

In [26]:
mask_not_nan

      HR    MAP     CI
0   True   True   True
1   True  False   True
2  False   True   True
3   True   True  False
4   True   True   True

In [27]:
df[mask_not_nan]

     HR    MAP   CI
0  70.0   93.0  2.6
1  85.0    NaN  3.0
2   NaN  100.0  3.2
3  90.0  105.0  NaN
4  76.0   88.0  2.8

In [23]:
from sklearn.metrics import mean_squared_error

mask_not_nan = ~df.isna()          # True wherever original value is present
orig_vals    = df[mask_not_nan]    # drop NaNs


for n in [3, 5, 10, 20]:
    imputer = IterativeImputer(estimator=BayesianRidge(), n_nearest_features=n, random_state=0)
    df_imputed = imputer.fit_transform(df)
    mse = mean_squared_error(orig_vals.values, df_imputed)
    print(f"n_nearest_features={n} => MSE: {mse:.4f}")

ValueError: Input contains NaN.